# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260119-862
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_formulari.models.ruolo_conferma_copia_cartacea import RuoloConfermaCopiaCartacea

class TestRuoloConfermaCopiaCartacea(unittest.TestCase):
    """RuoloConfermaCopiaCartacea unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRuoloConfermaCopiaCartacea(self):
        """Test RuoloConfermaCopiaCartacea"""
        # inst = RuoloConfermaCopiaCartacea()

if __name__ == '__main__':
    unittest.main()
