# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260119-862
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_formulari.models.tipo_analisi_classificazione import TipoAnalisiClassificazione

class TestTipoAnalisiClassificazione(unittest.TestCase):
    """TipoAnalisiClassificazione unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTipoAnalisiClassificazione(self):
        """Test TipoAnalisiClassificazione"""
        # inst = TipoAnalisiClassificazione()

if __name__ == '__main__':
    unittest.main()
