# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20251218-834
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_formulari.models.quantita_rifiuto_model import QuantitaRifiutoModel

class TestQuantitaRifiutoModel(unittest.TestCase):
    """QuantitaRifiutoModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QuantitaRifiutoModel:
        """Test QuantitaRifiutoModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QuantitaRifiutoModel`
        """
        model = QuantitaRifiutoModel()
        if include_optional:
            return QuantitaRifiutoModel(
                quantita = rentri_formulari.models.quantita_model.QuantitaModel(
                    valore = 1.337, 
                    unita_misura = null, ),
                verificato_in_partenza = True,
                numero_colli = '',
                rinfusa = True
            )
        else:
            return QuantitaRifiutoModel(
                quantita = rentri_formulari.models.quantita_model.QuantitaModel(
                    valore = 1.337, 
                    unita_misura = null, ),
        )
        """

    def testQuantitaRifiutoModel(self):
        """Test QuantitaRifiutoModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
