# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20250114-507
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_formulari.api.trasmissione_dati_soggetto_delegato_api import TrasmissioneDatiSoggettoDelegatoApi


class TestTrasmissioneDatiSoggettoDelegatoApi(unittest.TestCase):
    """TrasmissioneDatiSoggettoDelegatoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TrasmissioneDatiSoggettoDelegatoApi()

    def tearDown(self) -> None:
        pass

    def test_trasmissioni_soggetto_delegato_num_iscr_sito_get(self) -> None:
        """Test case for trasmissioni_soggetto_delegato_num_iscr_sito_get

        Trasmissioni effettuate
        """
        pass

    def test_trasmissioni_soggetto_delegato_num_iscr_sito_identificativo_annulla_delete(self) -> None:
        """Test case for trasmissioni_soggetto_delegato_num_iscr_sito_identificativo_annulla_delete

        Annulla trasmissione di dati del FIR digitale
        """
        pass

    def test_trasmissioni_soggetto_delegato_num_iscr_sito_identificativo_get(self) -> None:
        """Test case for trasmissioni_soggetto_delegato_num_iscr_sito_identificativo_get

        Dettaglio trasmissione
        """
        pass

    def test_trasmissioni_soggetto_delegato_num_iscr_sito_numero_fir_estrai_post(self) -> None:
        """Test case for trasmissioni_soggetto_delegato_num_iscr_sito_numero_fir_estrai_post

        🔁[ASYNC] Estrazione dati per FIR digitale
        """
        pass

    def test_trasmissioni_soggetto_delegato_num_iscr_sito_post(self) -> None:
        """Test case for trasmissioni_soggetto_delegato_num_iscr_sito_post

        Trasmette i dati del FIR digitale
        """
        pass


if __name__ == '__main__':
    unittest.main()
