# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260119-862
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_formulari.models.copia_cartacea_model import CopiaCartaceaModel  # noqa: E501

class TestCopiaCartaceaModel(unittest.TestCase):
    """CopiaCartaceaModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CopiaCartaceaModel:
        """Test CopiaCartaceaModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CopiaCartaceaModel`
        """
        model = CopiaCartaceaModel()  # noqa: E501
        if include_optional:
            return CopiaCartaceaModel(
                file_content = 'YQ==',
                nome_file = '0',
                mime = '0',
                numero_fir = 'WPQZYQ ) ._),,#_**&,\"%\"* - *- !'# 1757701929816286488291663/.$'\"&(_#+% #\"&%-/*- )!./ !),+#/)B0',
                data_emissione = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                produttore = rentri_formulari.models.copia_cartacea_soggetto_info.CopiaCartaceaSoggettoInfo(
                    nazione_id = '', 
                    identificativo = '01234', 
                    codice_fiscale = '01234', 
                    denominazione = '0', 
                    num_iscr_sito = '', ),
                trasportatori = [
                    rentri_formulari.models.copia_cartacea_soggetto_info.CopiaCartaceaSoggettoInfo(
                        nazione_id = '', 
                        identificativo = '01234', 
                        codice_fiscale = '01234', 
                        denominazione = '0', 
                        num_iscr_sito = '', )
                    ],
                intermediari = [
                    rentri_formulari.models.copia_cartacea_soggetto_info.CopiaCartaceaSoggettoInfo(
                        nazione_id = '', 
                        identificativo = '01234', 
                        codice_fiscale = '01234', 
                        denominazione = '0', 
                        num_iscr_sito = '', )
                    ],
                note = ''
            )
        else:
            return CopiaCartaceaModel(
                file_content = 'YQ==',
                nome_file = '0',
                mime = '0',
                numero_fir = 'WPQZYQ ) ._),,#_**&,\"%\"* - *- !'# 1757701929816286488291663/.$'\"&(_#+% #\"&%-/*- )!./ !),+#/)B0',
                data_emissione = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                produttore = rentri_formulari.models.copia_cartacea_soggetto_info.CopiaCartaceaSoggettoInfo(
                    nazione_id = '', 
                    identificativo = '01234', 
                    codice_fiscale = '01234', 
                    denominazione = '0', 
                    num_iscr_sito = '', ),
        )
        """

    def testCopiaCartaceaModel(self):
        """Test CopiaCartaceaModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
