# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20251218-834
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_formulari.models.status_response_enum import StatusResponseEnum

class TestStatusResponseEnum(unittest.TestCase):
    """StatusResponseEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatusResponseEnum(self):
        """Test StatusResponseEnum"""
        # inst = StatusResponseEnum()

if __name__ == '__main__':
    unittest.main()
