# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20250114-507
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_formulari.models.dati_trasbordo_parziale_origine_model import DatiTrasbordoParzialeOrigineModel  # noqa: E501

class TestDatiTrasbordoParzialeOrigineModel(unittest.TestCase):
    """DatiTrasbordoParzialeOrigineModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatiTrasbordoParzialeOrigineModel:
        """Test DatiTrasbordoParzialeOrigineModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatiTrasbordoParzialeOrigineModel`
        """
        model = DatiTrasbordoParzialeOrigineModel()  # noqa: E501
        if include_optional:
            return DatiTrasbordoParzialeOrigineModel(
                numero_fir_origine = 'WPQZYQ ) ._),,#_**&,\"%\"* - *- !'# 1757701929816286488291663/.$'\"&(_#+% #\"&%-/*- )!./ !),+#/)B0',
                produttore_originario = rentri_formulari.models.dati_produttore_originario_model.DatiProduttoreOriginarioModel(
                    nazione_id = '', 
                    denominazione = '0', 
                    codice_fiscale = '01234', ),
                causale = '0'
            )
        else:
            return DatiTrasbordoParzialeOrigineModel(
                numero_fir_origine = 'WPQZYQ ) ._),,#_**&,\"%\"* - *- !'# 1757701929816286488291663/.$'\"&(_#+% #\"&%-/*- )!./ !),+#/)B0',
                produttore_originario = rentri_formulari.models.dati_produttore_originario_model.DatiProduttoreOriginarioModel(
                    nazione_id = '', 
                    denominazione = '0', 
                    codice_fiscale = '01234', ),
                causale = '0',
        )
        """

    def testDatiTrasbordoParzialeOrigineModel(self):
        """Test DatiTrasbordoParzialeOrigineModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
