# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260211-891
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_formulari.api.formulario_digitale_api import FormularioDigitaleApi


class TestFormularioDigitaleApi(unittest.TestCase):
    """FormularioDigitaleApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FormularioDigitaleApi()

    def tearDown(self) -> None:
        pass

    def test_count_get(self) -> None:
        """Test case for count_get

        Conteggio formulari
        """
        pass

    def test_numero_fir_accettazione_post(self) -> None:
        """Test case for numero_fir_accettazione_post

        🔁[ASYNC] Accettazione FIR
        """
        pass

    def test_numero_fir_acquisizione_firma_post(self) -> None:
        """Test case for numero_fir_acquisizione_firma_post

        🔁[ASYNC] Imposta dati firma
        """
        pass

    def test_numero_fir_acquisizione_num_iscr_sito_post(self) -> None:
        """Test case for numero_fir_acquisizione_num_iscr_sito_post

        ⚠️[DEPRECATO] - utilizzare /{numeroFIR}/acquisizione-visibilita/{numIscrSito} - Acquisizione visibilità FIR
        """
        pass

    def test_numero_fir_acquisizione_visibilita_num_iscr_sito_post(self) -> None:
        """Test case for numero_fir_acquisizione_visibilita_num_iscr_sito_post

        Acquisizione visibilità FIR
        """
        pass

    def test_numero_fir_allegato_allegato_id_delete(self) -> None:
        """Test case for numero_fir_allegato_allegato_id_delete

        🔁[ASYNC] Rimuove un allegato
        """
        pass

    def test_numero_fir_allegato_allegato_id_get(self) -> None:
        """Test case for numero_fir_allegato_allegato_id_get

        Download un allegato
        """
        pass

    def test_numero_fir_allegato_post(self) -> None:
        """Test case for numero_fir_allegato_post

        🔁[ASYNC] Aggiunge un allegato
        """
        pass

    def test_numero_fir_annotazione_post(self) -> None:
        """Test case for numero_fir_annotazione_post

        🔁[ASYNC] Aggiunge annotazione
        """
        pass

    def test_numero_fir_annulla_fir_post(self) -> None:
        """Test case for numero_fir_annulla_fir_post

        🔁[ASYNC] Annullamento FIR
        """
        pass

    def test_numero_fir_annulla_post(self) -> None:
        """Test case for numero_fir_annulla_post

        🔁[ASYNC] ⚠️[DEPRECATO] - utilizzare /{numeroFIR}/annulla-fir - Annullamento FIR
        """
        pass

    def test_numero_fir_azioni_get(self) -> None:
        """Test case for numero_fir_azioni_get

        Operazioni disponibili
        """
        pass

    def test_numero_fir_destinatario_post(self) -> None:
        """Test case for numero_fir_destinatario_post

        🔁[ASYNC] Aggiunge nuovo destinatario
        """
        pass

    def test_numero_fir_get(self) -> None:
        """Test case for numero_fir_get

        Dettaglio FIR
        """
        pass

    def test_numero_fir_hash_post(self) -> None:
        """Test case for numero_fir_hash_post

        🔁[ASYNC] Calcolo del codice hash da firmare
        """
        pass

    def test_numero_fir_invia_a_dispositivo_post(self) -> None:
        """Test case for numero_fir_invia_a_dispositivo_post

        Invia il FIR ad un dispositivo
        """
        pass

    def test_numero_fir_note_annullamento_post(self) -> None:
        """Test case for numero_fir_note_annullamento_post

        🔁[ASYNC] Imposta le note di annullamento del FIR
        """
        pass

    def test_numero_fir_pdf_get(self) -> None:
        """Test case for numero_fir_pdf_get

        Stampa PDF del FIR
        """
        pass

    def test_numero_fir_put(self) -> None:
        """Test case for numero_fir_put

        🔁[ASYNC] Modifica FIR
        """
        pass

    def test_numero_fir_quantita_post(self) -> None:
        """Test case for numero_fir_quantita_post

        🔁[ASYNC] Imposta quantità
        """
        pass

    def test_numero_fir_reset_post(self) -> None:
        """Test case for numero_fir_reset_post

        🔁[ASYNC] Reset stato
        """
        pass

    def test_numero_fir_respingi_post(self) -> None:
        """Test case for numero_fir_respingi_post

        ⚠️[DEPRECATO] - utilizzare /{numeroFIR}/rilascio-visibilita/{numIscrSito} - Rilascio visibilità FIR
        """
        pass

    def test_numero_fir_rilascio_visibilita_num_iscr_sito_post(self) -> None:
        """Test case for numero_fir_rilascio_visibilita_num_iscr_sito_post

        Rilascio visibilità FIR
        """
        pass

    def test_numero_fir_rollback_firma_post(self) -> None:
        """Test case for numero_fir_rollback_firma_post

        🔁[ASYNC] Rollback dell'ultima firma
        """
        pass

    def test_numero_fir_sosta_tecnica_post(self) -> None:
        """Test case for numero_fir_sosta_tecnica_post

        🔁[ASYNC] Aggiunge sosta tecnica
        """
        pass

    def test_numero_fir_stato_get(self) -> None:
        """Test case for numero_fir_stato_get

        Stato FIR
        """
        pass

    def test_numero_fir_trasbordo_parziale_post(self) -> None:
        """Test case for numero_fir_trasbordo_parziale_post

        🔁[ASYNC] Aggiunge trasbordo parziale
        """
        pass

    def test_numero_fir_trasbordo_totale_post(self) -> None:
        """Test case for numero_fir_trasbordo_totale_post

        🔁[ASYNC] Aggiunge trasbordo totale
        """
        pass

    def test_numero_fir_trasporto_post(self) -> None:
        """Test case for numero_fir_trasporto_post

        🔁[ASYNC] Aggiunge dati trasporto
        """
        pass

    def test_numero_fir_xfir_get(self) -> None:
        """Test case for numero_fir_xfir_get

        Download xFIR
        """
        pass

    def test_numero_fir_xfir_post(self) -> None:
        """Test case for numero_fir_xfir_post

        🔁[ASYNC] Upload xFIR
        """
        pass

    def test_root_get(self) -> None:
        """Test case for root_get

        Elenco formulari
        """
        pass

    def test_root_post(self) -> None:
        """Test case for root_post

        🔁[ASYNC] Crea FIR
        """
        pass

    def test_xfir_valida_post(self) -> None:
        """Test case for xfir_valida_post

        🔁[ASYNC] Validazione xFIR
        """
        pass


if __name__ == '__main__':
    unittest.main()
