# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260211-891
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_formulari.models.dati_trasmissione_partenza_model import DatiTrasmissionePartenzaModel  # noqa: E501

class TestDatiTrasmissionePartenzaModel(unittest.TestCase):
    """DatiTrasmissionePartenzaModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatiTrasmissionePartenzaModel:
        """Test DatiTrasmissionePartenzaModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatiTrasmissionePartenzaModel`
        """
        model = DatiTrasmissionePartenzaModel()  # noqa: E501
        if include_optional:
            return DatiTrasmissionePartenzaModel(
                numero_fir = 'WPQZYQ ) ._),,#_**&,\"%\"* - *- !'# 1757701929816286488291663/.$'\"&(_#+% #\"&%-/*- )!./ !),+#/)B0',
                produttore = rentri_formulari.models.dati_produttore_trasmissione_model.DatiProduttoreTrasmissioneModel(
                    denominazione = '0', 
                    codice_fiscale = '01234', 
                    nazione_id = '', 
                    indirizzo = null, 
                    num_iscr_sito = 'OP0480ZGC880015-CM0217', 
                    luogo_produzione = null, 
                    autorizzazione = null, 
                    detentore = True, 
                    numero_iscrizione_albo = 'AE/807288', ),
                trasbordo_parziale_origine = rentri_formulari.models.dati_trasbordo_parziale_origine_model.DatiTrasbordoParzialeOrigineModel(
                    numero_fir_origine = 'WPQZYQ ) ._),,#_**&,\"%\"* - *- !'# 1757701929816286488291663/.$'\"&(_#+% #\"&%-/*- )!./ !),+#/)B0', 
                    produttore_originario = null, 
                    causale = '0', ),
                destinatario = rentri_formulari.models.dati_destinatario_trasmissione_model.DatiDestinatarioTrasmissioneModel(
                    denominazione = '0', 
                    codice_fiscale = '01234', 
                    nazione_id = '', 
                    indirizzo = null, 
                    num_iscr_sito = 'OP0480ZGC880015-CM0217', 
                    autorizzazione = null, 
                    attivita = null, 
                    numero_iscrizione_albo = 'AE/807288', ),
                trasportatori = [
                    rentri_formulari.models.dati_trasportatore_trasmissione_model.DatiTrasportatoreTrasmissioneModel(
                        denominazione = '0', 
                        codice_fiscale = '01234', 
                        nazione_id = '', 
                        trasportatore_id = 1, 
                        num_iscr_sito = 'OP0480ZGC880015-CM0217', 
                        tipo_trasporto = null, 
                        numero_iscrizione_albo = 'AE/807288', )
                    ],
                data_emissione = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                intermediari = [
                    rentri_formulari.models.dati_intermediari_formulario_model.DatiIntermediariFormularioModel(
                        denominazione = '0', 
                        codice_fiscale = '01234', 
                        nazione_id = '', 
                        numero_iscrizione_albo = 'AE/807288', )
                    ],
                rifiuto = rentri_formulari.models.dati_rifiuto_model.DatiRifiutoModel(
                    codice_eer = '0', 
                    descrizione = '', 
                    provenienza = null, 
                    caratteristiche_chimico_fisiche = '', 
                    caratteristiche_pericolo = [
                        'HP01'
                        ], 
                    stato_fisico = null, 
                    quantita = null, 
                    verificato_in_partenza = True, 
                    trasporto_adr = True, 
                    dati_adr = null, 
                    analisi_classificazione = null, 
                    numero_colli = '', 
                    rinfusa = True, ),
                annotazioni = ''
            )
        else:
            return DatiTrasmissionePartenzaModel(
                numero_fir = 'WPQZYQ ) ._),,#_**&,\"%\"* - *- !'# 1757701929816286488291663/.$'\"&(_#+% #\"&%-/*- )!./ !),+#/)B0',
                destinatario = rentri_formulari.models.dati_destinatario_trasmissione_model.DatiDestinatarioTrasmissioneModel(
                    denominazione = '0', 
                    codice_fiscale = '01234', 
                    nazione_id = '', 
                    indirizzo = null, 
                    num_iscr_sito = 'OP0480ZGC880015-CM0217', 
                    autorizzazione = null, 
                    attivita = null, 
                    numero_iscrizione_albo = 'AE/807288', ),
                trasportatori = [
                    rentri_formulari.models.dati_trasportatore_trasmissione_model.DatiTrasportatoreTrasmissioneModel(
                        denominazione = '0', 
                        codice_fiscale = '01234', 
                        nazione_id = '', 
                        trasportatore_id = 1, 
                        num_iscr_sito = 'OP0480ZGC880015-CM0217', 
                        tipo_trasporto = null, 
                        numero_iscrizione_albo = 'AE/807288', )
                    ],
                data_emissione = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                rifiuto = rentri_formulari.models.dati_rifiuto_model.DatiRifiutoModel(
                    codice_eer = '0', 
                    descrizione = '', 
                    provenienza = null, 
                    caratteristiche_chimico_fisiche = '', 
                    caratteristiche_pericolo = [
                        'HP01'
                        ], 
                    stato_fisico = null, 
                    quantita = null, 
                    verificato_in_partenza = True, 
                    trasporto_adr = True, 
                    dati_adr = null, 
                    analisi_classificazione = null, 
                    numero_colli = '', 
                    rinfusa = True, ),
        )
        """

    def testDatiTrasmissionePartenzaModel(self):
        """Test DatiTrasmissionePartenzaModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
