# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20250114-507
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_formulari.models.esito_carica_copia_cartacea_model import EsitoCaricaCopiaCartaceaModel  # noqa: E501

class TestEsitoCaricaCopiaCartaceaModel(unittest.TestCase):
    """EsitoCaricaCopiaCartaceaModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EsitoCaricaCopiaCartaceaModel:
        """Test EsitoCaricaCopiaCartaceaModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EsitoCaricaCopiaCartaceaModel`
        """
        model = EsitoCaricaCopiaCartaceaModel()  # noqa: E501
        if include_optional:
            return EsitoCaricaCopiaCartaceaModel(
                identificativo = ''
            )
        else:
            return EsitoCaricaCopiaCartaceaModel(
        )
        """

    def testEsitoCaricaCopiaCartaceaModel(self):
        """Test EsitoCaricaCopiaCartaceaModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
