# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20250114-507
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_formulari.models.dati_trasportatore_formulario_base_model import DatiTrasportatoreFormularioBaseModel

class TestDatiTrasportatoreFormularioBaseModel(unittest.TestCase):
    """DatiTrasportatoreFormularioBaseModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatiTrasportatoreFormularioBaseModel:
        """Test DatiTrasportatoreFormularioBaseModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatiTrasportatoreFormularioBaseModel`
        """
        model = DatiTrasportatoreFormularioBaseModel()
        if include_optional:
            return DatiTrasportatoreFormularioBaseModel(
                tipo_trasporto = 'Terrestre',
                numero_iscrizione_albo = 'AE/807288'
            )
        else:
            return DatiTrasportatoreFormularioBaseModel(
                tipo_trasporto = 'Terrestre',
        )
        """

    def testDatiTrasportatoreFormularioBaseModel(self):
        """Test DatiTrasportatoreFormularioBaseModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
