# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260211-891
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_formulari.models.caratteristiche_pericolo import CaratteristichePericolo  # noqa: E501

class TestCaratteristichePericolo(unittest.TestCase):
    """CaratteristichePericolo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCaratteristichePericolo(self):
        """Test CaratteristichePericolo"""
        # inst = CaratteristichePericolo()

if __name__ == '__main__':
    unittest.main()
