# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20250114-507
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_formulari.models.quantita_model import QuantitaModel  # noqa: E501

class TestQuantitaModel(unittest.TestCase):
    """QuantitaModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QuantitaModel:
        """Test QuantitaModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QuantitaModel`
        """
        model = QuantitaModel()  # noqa: E501
        if include_optional:
            return QuantitaModel(
                valore = 1.337,
                unita_misura = 'kg'
            )
        else:
            return QuantitaModel(
                valore = 1.337,
                unita_misura = 'kg',
        )
        """

    def testQuantitaModel(self):
        """Test QuantitaModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
