# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260119-862
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_formulari.models.operazione import Operazione

class TestOperazione(unittest.TestCase):
    """Operazione unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOperazione(self):
        """Test Operazione"""
        # inst = Operazione()

if __name__ == '__main__':
    unittest.main()
