# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260211-891
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_formulari.models.esito_copia_cartacea_model import EsitoCopiaCartaceaModel  # noqa: E501

class TestEsitoCopiaCartaceaModel(unittest.TestCase):
    """EsitoCopiaCartaceaModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EsitoCopiaCartaceaModel:
        """Test EsitoCopiaCartaceaModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EsitoCopiaCartaceaModel`
        """
        model = EsitoCopiaCartaceaModel()  # noqa: E501
        if include_optional:
            return EsitoCopiaCartaceaModel(
                esito = rentri_formulari.models.esito_carica_copia_cartacea_model.EsitoCaricaCopiaCartaceaModel(
                    identificativo = '', ),
                tipo = '',
                transazione_id = '',
                validazione = [
                    rentri_formulari.models.esito_messaggio_model.EsitoMessaggioModel(
                        indice = 56, 
                        campo = '', 
                        tipo = null, 
                        codice_messaggio = '', 
                        parametri = [
                            null
                            ], )
                    ],
                errore = True,
                tempo_elaborazione = ''
            )
        else:
            return EsitoCopiaCartaceaModel(
        )
        """

    def testEsitoCopiaCartaceaModel(self):
        """Test EsitoCopiaCartaceaModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
