# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20250114-507
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_formulari.models.dati_sosta_tecnica_trasmissione_model import DatiSostaTecnicaTrasmissioneModel

class TestDatiSostaTecnicaTrasmissioneModel(unittest.TestCase):
    """DatiSostaTecnicaTrasmissioneModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatiSostaTecnicaTrasmissioneModel:
        """Test DatiSostaTecnicaTrasmissioneModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatiSostaTecnicaTrasmissioneModel`
        """
        model = DatiSostaTecnicaTrasmissioneModel()
        if include_optional:
            return DatiSostaTecnicaTrasmissioneModel(
                trasportatore_id = 56,
                luogo_stazionamento = '0',
                data_ora_sospensione = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                data_ora_ripresa = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return DatiSostaTecnicaTrasmissioneModel(
                trasportatore_id = 56,
                luogo_stazionamento = '0',
                data_ora_sospensione = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                data_ora_ripresa = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testDatiSostaTecnicaTrasmissioneModel(self):
        """Test DatiSostaTecnicaTrasmissioneModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
