# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260211-891
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_formulari.models.nuovo_formulario_model_dati_trasporto_partenza import NuovoFormularioModelDatiTrasportoPartenza  # noqa: E501

class TestNuovoFormularioModelDatiTrasportoPartenza(unittest.TestCase):
    """NuovoFormularioModelDatiTrasportoPartenza unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NuovoFormularioModelDatiTrasportoPartenza:
        """Test NuovoFormularioModelDatiTrasportoPartenza
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NuovoFormularioModelDatiTrasportoPartenza`
        """
        model = NuovoFormularioModelDatiTrasportoPartenza()  # noqa: E501
        if include_optional:
            return NuovoFormularioModelDatiTrasportoPartenza(
                conducente = rentri_formulari.models.conducente_model.ConducenteModel(
                    nome = '0', 
                    cognome = '0', ),
                targa_automezzo = '',
                targa_rimorchio = '',
                percorso = '',
                presa_in_carico_rimorchio_precedente = True,
                data_ora_inizio_trasporto = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                annotazioni = '',
                nave = '0',
                imdg = True,
                treno = '0',
                rid = True,
                tratta = ''
            )
        else:
            return NuovoFormularioModelDatiTrasportoPartenza(
                conducente = rentri_formulari.models.conducente_model.ConducenteModel(
                    nome = '0', 
                    cognome = '0', ),
                data_ora_inizio_trasporto = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                nave = '0',
                treno = '0',
        )
        """

    def testNuovoFormularioModelDatiTrasportoPartenza(self):
        """Test NuovoFormularioModelDatiTrasportoPartenza"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
