# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20251218-834
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_formulari.models.dettaglio_formulario_dati_trasporto_inner import DettaglioFormularioDatiTrasportoInner

class TestDettaglioFormularioDatiTrasportoInner(unittest.TestCase):
    """DettaglioFormularioDatiTrasportoInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DettaglioFormularioDatiTrasportoInner:
        """Test DettaglioFormularioDatiTrasportoInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DettaglioFormularioDatiTrasportoInner`
        """
        model = DettaglioFormularioDatiTrasportoInner()
        if include_optional:
            return DettaglioFormularioDatiTrasportoInner(
                tipo_trasporto = 'Terrestre',
                dati_firma_trasportatore = rentri_formulari.models.dati_firma_result.DatiFirmaResult(
                    denominazione_firmatario = '', 
                    identificativo_firmatario = '', 
                    data_firma = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    identificativo_utente = '', 
                    credentials_id = '', 
                    nome_certificato_ca = '', ),
                trasportatore_id = 56,
                conducente = rentri_formulari.models.conducente_model.ConducenteModel(
                    nome = '0', 
                    cognome = '0', ),
                targa_automezzo = '',
                targa_rimorchio = '',
                percorso = '',
                presa_in_carico_rimorchio_precedente = True,
                data_ora_inizio_trasporto = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                annotazioni = '',
                nave = '0',
                imdg = True,
                treno = '0',
                rid = True,
                tratta = ''
            )
        else:
            return DettaglioFormularioDatiTrasportoInner(
                conducente = rentri_formulari.models.conducente_model.ConducenteModel(
                    nome = '0', 
                    cognome = '0', ),
                data_ora_inizio_trasporto = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                nave = '0',
                treno = '0',
        )
        """

    def testDettaglioFormularioDatiTrasportoInner(self):
        """Test DettaglioFormularioDatiTrasportoInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
