# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20250114-507
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_formulari.models.copia_cartacea_soggetto_info import CopiaCartaceaSoggettoInfo  # noqa: E501

class TestCopiaCartaceaSoggettoInfo(unittest.TestCase):
    """CopiaCartaceaSoggettoInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CopiaCartaceaSoggettoInfo:
        """Test CopiaCartaceaSoggettoInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CopiaCartaceaSoggettoInfo`
        """
        model = CopiaCartaceaSoggettoInfo()  # noqa: E501
        if include_optional:
            return CopiaCartaceaSoggettoInfo(
                nazione_id = '',
                identificativo = '01234',
                codice_fiscale = '01234',
                denominazione = '0',
                num_iscr_sito = ''
            )
        else:
            return CopiaCartaceaSoggettoInfo(
                codice_fiscale = '01234',
                denominazione = '0',
        )
        """

    def testCopiaCartaceaSoggettoInfo(self):
        """Test CopiaCartaceaSoggettoInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
