# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260119-862
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_formulari.models.stato_formulario import StatoFormulario  # noqa: E501

class TestStatoFormulario(unittest.TestCase):
    """StatoFormulario unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatoFormulario(self):
        """Test StatoFormulario"""
        # inst = StatoFormulario()

if __name__ == '__main__':
    unittest.main()
