# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20250114-507
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_formulari.models.unita_misura import UnitaMisura

class TestUnitaMisura(unittest.TestCase):
    """UnitaMisura unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnitaMisura(self):
        """Test UnitaMisura"""
        # inst = UnitaMisura()

if __name__ == '__main__':
    unittest.main()
