# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260119-862
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_formulari.models.causali_respingimento import CausaliRespingimento  # noqa: E501

class TestCausaliRespingimento(unittest.TestCase):
    """CausaliRespingimento unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCausaliRespingimento(self):
        """Test CausaliRespingimento"""
        # inst = CausaliRespingimento()

if __name__ == '__main__':
    unittest.main()
