# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20250114-507
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_formulari.models.dati_destinatario_formulario_model3 import DatiDestinatarioFormularioModel3  # noqa: E501

class TestDatiDestinatarioFormularioModel3(unittest.TestCase):
    """DatiDestinatarioFormularioModel3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatiDestinatarioFormularioModel3:
        """Test DatiDestinatarioFormularioModel3
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatiDestinatarioFormularioModel3`
        """
        model = DatiDestinatarioFormularioModel3()  # noqa: E501
        if include_optional:
            return DatiDestinatarioFormularioModel3(
                denominazione = '0',
                codice_fiscale = '01234',
                nazione_id = '',
                indirizzo = rentri_formulari.models.indirizzo_model.IndirizzoModel(
                    citta = null, 
                    indirizzo = '0', 
                    civico = '', 
                    cap = '', ),
                autorizzazione = rentri_formulari.models.autorizzazione_model.AutorizzazioneModel(
                    numero = '', 
                    tipo = null, ),
                attivita = 'R1',
                numero_iscrizione_albo = 'AE/807288'
            )
        else:
            return DatiDestinatarioFormularioModel3(
                denominazione = '0',
                codice_fiscale = '01234',
                indirizzo = rentri_formulari.models.indirizzo_model.IndirizzoModel(
                    citta = null, 
                    indirizzo = '0', 
                    civico = '', 
                    cap = '', ),
        )
        """

    def testDatiDestinatarioFormularioModel3(self):
        """Test DatiDestinatarioFormularioModel3"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
