# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260211-891
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_formulari.models.dati_trasbordo_totale_trasmissione_model import DatiTrasbordoTotaleTrasmissioneModel  # noqa: E501

class TestDatiTrasbordoTotaleTrasmissioneModel(unittest.TestCase):
    """DatiTrasbordoTotaleTrasmissioneModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatiTrasbordoTotaleTrasmissioneModel:
        """Test DatiTrasbordoTotaleTrasmissioneModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatiTrasbordoTotaleTrasmissioneModel`
        """
        model = DatiTrasbordoTotaleTrasmissioneModel()  # noqa: E501
        if include_optional:
            return DatiTrasbordoTotaleTrasmissioneModel(
                trasportatore_id = 1,
                id_trasportatore_trasbordo = 56,
                trasportatore = rentri_formulari.models.dati_trasportatore_trasmissione_model.DatiTrasportatoreTrasmissioneModel(
                    denominazione = '0', 
                    codice_fiscale = '01234', 
                    nazione_id = '', 
                    trasportatore_id = 1, 
                    num_iscr_sito = 'OP0480ZGC880015-CM0217', 
                    tipo_trasporto = null, 
                    numero_iscrizione_albo = 'AE/807288', ),
                presa_in_carico = None
            )
        else:
            return DatiTrasbordoTotaleTrasmissioneModel(
                trasportatore_id = 1,
                trasportatore = rentri_formulari.models.dati_trasportatore_trasmissione_model.DatiTrasportatoreTrasmissioneModel(
                    denominazione = '0', 
                    codice_fiscale = '01234', 
                    nazione_id = '', 
                    trasportatore_id = 1, 
                    num_iscr_sito = 'OP0480ZGC880015-CM0217', 
                    tipo_trasporto = null, 
                    numero_iscrizione_albo = 'AE/807288', ),
                presa_in_carico = None,
        )
        """

    def testDatiTrasbordoTotaleTrasmissioneModel(self):
        """Test DatiTrasbordoTotaleTrasmissioneModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
