# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20250114-507
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_formulari.models.dati_trasbordo_parziale_model import DatiTrasbordoParzialeModel  # noqa: E501

class TestDatiTrasbordoParzialeModel(unittest.TestCase):
    """DatiTrasbordoParzialeModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatiTrasbordoParzialeModel:
        """Test DatiTrasbordoParzialeModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatiTrasbordoParzialeModel`
        """
        model = DatiTrasbordoParzialeModel()  # noqa: E501
        if include_optional:
            return DatiTrasbordoParzialeModel(
                numero_fir = '0',
                trasportatore = rentri_formulari.models.dati_trasportatore_trasbordo_model.DatiTrasportatoreTrasbordoModel(
                    nazione_id = '', 
                    denominazione = '0', 
                    codice_fiscale = '01234', 
                    numero_iscrizione_albo = 'AE/807288', ),
                quantita_residua = rentri_formulari.models.quantita_model.QuantitaModel(
                    valore = 1.337, 
                    unita_misura = null, ),
                causale = '0'
            )
        else:
            return DatiTrasbordoParzialeModel(
                numero_fir = '0',
                trasportatore = rentri_formulari.models.dati_trasportatore_trasbordo_model.DatiTrasportatoreTrasbordoModel(
                    nazione_id = '', 
                    denominazione = '0', 
                    codice_fiscale = '01234', 
                    numero_iscrizione_albo = 'AE/807288', ),
                quantita_residua = rentri_formulari.models.quantita_model.QuantitaModel(
                    valore = 1.337, 
                    unita_misura = null, ),
                causale = '0',
        )
        """

    def testDatiTrasbordoParzialeModel(self):
        """Test DatiTrasbordoParzialeModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
