# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20250114-507
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_formulari.models.copia_cartacea_conferma_model import CopiaCartaceaConfermaModel

class TestCopiaCartaceaConfermaModel(unittest.TestCase):
    """CopiaCartaceaConfermaModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CopiaCartaceaConfermaModel:
        """Test CopiaCartaceaConfermaModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CopiaCartaceaConfermaModel`
        """
        model = CopiaCartaceaConfermaModel()
        if include_optional:
            return CopiaCartaceaConfermaModel(
                identificativo = '0',
                num_iscr_sito = '',
                ruolo = 'Produttore',
                respingi = True
            )
        else:
            return CopiaCartaceaConfermaModel(
                identificativo = '0',
        )
        """

    def testCopiaCartaceaConfermaModel(self):
        """Test CopiaCartaceaConfermaModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
