# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20250114-507
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_formulari.models.tipo_ricerca import TipoRicerca  # noqa: E501

class TestTipoRicerca(unittest.TestCase):
    """TipoRicerca unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTipoRicerca(self):
        """Test TipoRicerca"""
        # inst = TipoRicerca()

if __name__ == '__main__':
    unittest.main()
