# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260211-891
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_formulari.models.dati_rifiuto_model import DatiRifiutoModel  # noqa: E501

class TestDatiRifiutoModel(unittest.TestCase):
    """DatiRifiutoModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatiRifiutoModel:
        """Test DatiRifiutoModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatiRifiutoModel`
        """
        model = DatiRifiutoModel()  # noqa: E501
        if include_optional:
            return DatiRifiutoModel(
                codice_eer = '0',
                descrizione = '',
                provenienza = 'U',
                caratteristiche_chimico_fisiche = '',
                caratteristiche_pericolo = [
                    'HP01'
                    ],
                stato_fisico = 'SP',
                quantita = rentri_formulari.models.quantita_model.QuantitaModel(
                    valore = 1.337, 
                    unita_misura = null, ),
                verificato_in_partenza = True,
                trasporto_adr = True,
                dati_adr = rentri_formulari.models.normativa_adr_model.NormativaADRModel(
                    numero_onu = '', 
                    classe = '', 
                    note = '', ),
                analisi_classificazione = rentri_formulari.models.analisi_classificazione_model.AnalisiClassificazioneModel(
                    tipo = null, 
                    numero = '0', 
                    data = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                numero_colli = '',
                rinfusa = True
            )
        else:
            return DatiRifiutoModel(
                codice_eer = '0',
                provenienza = 'U',
                stato_fisico = 'SP',
        )
        """

    def testDatiRifiutoModel(self):
        """Test DatiRifiutoModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
