# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20250114-507
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_formulari.models.dati_trasporto_trasmissione_base_model1 import DatiTrasportoTrasmissioneBaseModel1

class TestDatiTrasportoTrasmissioneBaseModel1(unittest.TestCase):
    """DatiTrasportoTrasmissioneBaseModel1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatiTrasportoTrasmissioneBaseModel1:
        """Test DatiTrasportoTrasmissioneBaseModel1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatiTrasportoTrasmissioneBaseModel1`
        """
        model = DatiTrasportoTrasmissioneBaseModel1()
        if include_optional:
            return DatiTrasportoTrasmissioneBaseModel1(
                treno = '0',
                tratta = '',
                rid = True,
                trasportatore_id = 56,
                data_ora_inizio_trasporto = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                annotazioni = '',
                conducente = rentri_formulari.models.conducente_model.ConducenteModel(
                    nome = '0', 
                    cognome = '0', ),
                targa_automezzo = '',
                targa_rimorchio = '',
                percorso = '',
                nave = '0',
                imdg = True
            )
        else:
            return DatiTrasportoTrasmissioneBaseModel1(
                treno = '0',
                trasportatore_id = 56,
                data_ora_inizio_trasporto = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                conducente = rentri_formulari.models.conducente_model.ConducenteModel(
                    nome = '0', 
                    cognome = '0', ),
                nave = '0',
        )
        """

    def testDatiTrasportoTrasmissioneBaseModel1(self):
        """Test DatiTrasportoTrasmissioneBaseModel1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
