# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20250114-507
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_formulari.models.stati_fisici import StatiFisici  # noqa: E501

class TestStatiFisici(unittest.TestCase):
    """StatiFisici unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatiFisici(self):
        """Test StatiFisici"""
        # inst = StatiFisici()

if __name__ == '__main__':
    unittest.main()
