# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260119-862
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_formulari.models.dati_produttore_formulario_model import DatiProduttoreFormularioModel  # noqa: E501

class TestDatiProduttoreFormularioModel(unittest.TestCase):
    """DatiProduttoreFormularioModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatiProduttoreFormularioModel:
        """Test DatiProduttoreFormularioModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatiProduttoreFormularioModel`
        """
        model = DatiProduttoreFormularioModel()  # noqa: E501
        if include_optional:
            return DatiProduttoreFormularioModel(
                denominazione = '0',
                codice_fiscale = '01234',
                nazione_id = '',
                indirizzo = rentri_formulari.models.indirizzo_model.IndirizzoModel(
                    citta = null, 
                    indirizzo = '0', 
                    civico = '', 
                    cap = '', ),
                luogo_produzione = rentri_formulari.models.indirizzo_model.IndirizzoModel(
                    citta = null, 
                    indirizzo = '0', 
                    civico = '', 
                    cap = '', ),
                autorizzazione = rentri_formulari.models.autorizzazione_model.AutorizzazioneModel(
                    numero = '', 
                    tipo = null, ),
                detentore = True,
                numero_iscrizione_albo = 'AE/807288'
            )
        else:
            return DatiProduttoreFormularioModel(
                denominazione = '0',
                codice_fiscale = '01234',
                indirizzo = rentri_formulari.models.indirizzo_model.IndirizzoModel(
                    citta = null, 
                    indirizzo = '0', 
                    civico = '', 
                    cap = '', ),
        )
        """

    def testDatiProduttoreFormularioModel(self):
        """Test DatiProduttoreFormularioModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
