# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20251218-834
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_formulari.models.valida_xfir_model import ValidaXfirModel

class TestValidaXfirModel(unittest.TestCase):
    """ValidaXfirModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValidaXfirModel:
        """Test ValidaXfirModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValidaXfirModel`
        """
        model = ValidaXfirModel()
        if include_optional:
            return ValidaXfirModel(
                xfir = 'YQ=='
            )
        else:
            return ValidaXfirModel(
                xfir = 'YQ==',
        )
        """

    def testValidaXfirModel(self):
        """Test ValidaXfirModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
