# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260119-862
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_formulari.models.dati_notifica_push_carica_copia_digitale_model import DatiNotificaPushCaricaCopiaDigitaleModel  # noqa: E501

class TestDatiNotificaPushCaricaCopiaDigitaleModel(unittest.TestCase):
    """DatiNotificaPushCaricaCopiaDigitaleModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatiNotificaPushCaricaCopiaDigitaleModel:
        """Test DatiNotificaPushCaricaCopiaDigitaleModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatiNotificaPushCaricaCopiaDigitaleModel`
        """
        model = DatiNotificaPushCaricaCopiaDigitaleModel()  # noqa: E501
        if include_optional:
            return DatiNotificaPushCaricaCopiaDigitaleModel(
                proprieta = rentri_formulari.models.proprieta_dati_notifica_push_carica_copia_digitale_model.ProprietaDatiNotificaPushCaricaCopiaDigitaleModel(
                    identificativo = '', 
                    numero_fir = '', 
                    data_evento = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    tipo_accettazione = null, 
                    destinatario = null, ),
                tipo = ''
            )
        else:
            return DatiNotificaPushCaricaCopiaDigitaleModel(
        )
        """

    def testDatiNotificaPushCaricaCopiaDigitaleModel(self):
        """Test DatiNotificaPushCaricaCopiaDigitaleModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
