# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260211-891
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_formulari.models.dati_partenza_model_produttore import DatiPartenzaModelProduttore  # noqa: E501

class TestDatiPartenzaModelProduttore(unittest.TestCase):
    """DatiPartenzaModelProduttore unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatiPartenzaModelProduttore:
        """Test DatiPartenzaModelProduttore
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatiPartenzaModelProduttore`
        """
        model = DatiPartenzaModelProduttore()  # noqa: E501
        if include_optional:
            return DatiPartenzaModelProduttore(
                denominazione = '0',
                codice_fiscale = '01234',
                nazione_id = '',
                indirizzo = rentri_formulari.models.indirizzo_model.IndirizzoModel(
                    citta = null, 
                    indirizzo = '0', 
                    civico = '', 
                    cap = '', ),
                luogo_produzione = rentri_formulari.models.indirizzo_model.IndirizzoModel(
                    citta = null, 
                    indirizzo = '0', 
                    civico = '', 
                    cap = '', ),
                autorizzazione = rentri_formulari.models.autorizzazione_model.AutorizzazioneModel(
                    numero = '', 
                    tipo = null, ),
                detentore = True,
                numero_iscrizione_albo = 'AE/807288',
                num_iscr_sito = 'OP0480ZGC880015-CM02170'
            )
        else:
            return DatiPartenzaModelProduttore(
                denominazione = '0',
                codice_fiscale = '01234',
                indirizzo = rentri_formulari.models.indirizzo_model.IndirizzoModel(
                    citta = null, 
                    indirizzo = '0', 
                    civico = '', 
                    cap = '', ),
                num_iscr_sito = 'OP0480ZGC880015-CM02170',
        )
        """

    def testDatiPartenzaModelProduttore(self):
        """Test DatiPartenzaModelProduttore"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
