# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20251218-834
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_formulari.api.copia_fir_digitale_api import CopiaFIRDigitaleApi


class TestCopiaFIRDigitaleApi(unittest.TestCase):
    """CopiaFIRDigitaleApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CopiaFIRDigitaleApi()

    def tearDown(self) -> None:
        pass

    def test_copia_digitale_caricamento_num_iscr_sito_get(self) -> None:
        """Test case for copia_digitale_caricamento_num_iscr_sito_get

        Copie FIR digitali caricate
        """
        pass

    def test_copia_digitale_caricamento_num_iscr_sito_identificativo_delete(self) -> None:
        """Test case for copia_digitale_caricamento_num_iscr_sito_identificativo_delete

        Cancella copia FIR digitale
        """
        pass

    def test_copia_digitale_caricamento_num_iscr_sito_identificativo_documento_get(self) -> None:
        """Test case for copia_digitale_caricamento_num_iscr_sito_identificativo_documento_get

        Documento copia FIR digitale
        """
        pass

    def test_copia_digitale_caricamento_num_iscr_sito_identificativo_get(self) -> None:
        """Test case for copia_digitale_caricamento_num_iscr_sito_identificativo_get

        Dettaglio copia FIR digitale
        """
        pass

    def test_copia_digitale_caricamento_numero_fir_post(self) -> None:
        """Test case for copia_digitale_caricamento_numero_fir_post

        🔁[ASYNC] Carica copia FIR digitale
        """
        pass

    def test_copia_digitale_conferma_identificativo_soggetto_get(self) -> None:
        """Test case for copia_digitale_conferma_identificativo_soggetto_get

        Copie FIR digitali disponibili
        """
        pass

    def test_copia_digitale_conferma_identificativo_soggetto_identificativo_documento_get(self) -> None:
        """Test case for copia_digitale_conferma_identificativo_soggetto_identificativo_documento_get

        Documento copia FIR digitale disponibile
        """
        pass

    def test_copia_digitale_conferma_identificativo_soggetto_identificativo_get(self) -> None:
        """Test case for copia_digitale_conferma_identificativo_soggetto_identificativo_get

        Dettaglio copia digitale FIR disponibile
        """
        pass

    def test_copia_digitale_conferma_num_iscr_sito_identificativo_put(self) -> None:
        """Test case for copia_digitale_conferma_num_iscr_sito_identificativo_put

        Conferma copia FIR digitale disponibile
        """
        pass

    def test_copia_digitale_transazione_id_result_get(self) -> None:
        """Test case for copia_digitale_transazione_id_result_get

        ⚠️[DEPRECATO] - utilizzare /{transazioneId}/result - Esito transazione
        """
        pass

    def test_copia_digitale_transazione_id_status_get(self) -> None:
        """Test case for copia_digitale_transazione_id_status_get

        ⚠️[DEPRECATO] - utilizzare /{transazioneId}/status - Stato transazione
        """
        pass


if __name__ == '__main__':
    unittest.main()
