# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20251218-834
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_formulari.models.esito_get_hash_per_firma_model import EsitoGetHashPerFirmaModel

class TestEsitoGetHashPerFirmaModel(unittest.TestCase):
    """EsitoGetHashPerFirmaModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EsitoGetHashPerFirmaModel:
        """Test EsitoGetHashPerFirmaModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EsitoGetHashPerFirmaModel`
        """
        model = EsitoGetHashPerFirmaModel()
        if include_optional:
            return EsitoGetHashPerFirmaModel(
                hash_algorithm = '',
                digest_to_sign = '',
                token = '',
                versione = 56
            )
        else:
            return EsitoGetHashPerFirmaModel(
        )
        """

    def testEsitoGetHashPerFirmaModel(self):
        """Test EsitoGetHashPerFirmaModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
