# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20250114-507
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_formulari.models.dati_destinatario_formulario_model1 import DatiDestinatarioFormularioModel1  # noqa: E501

class TestDatiDestinatarioFormularioModel1(unittest.TestCase):
    """DatiDestinatarioFormularioModel1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatiDestinatarioFormularioModel1:
        """Test DatiDestinatarioFormularioModel1
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatiDestinatarioFormularioModel1`
        """
        model = DatiDestinatarioFormularioModel1()  # noqa: E501
        if include_optional:
            return DatiDestinatarioFormularioModel1(
                denominazione = '0',
                codice_fiscale = '01234',
                nazione_id = '',
                indirizzo = rentri_formulari.models.indirizzo_model.IndirizzoModel(
                    citta = null, 
                    indirizzo = '0', 
                    civico = '', 
                    cap = '', ),
                autorizzazione = rentri_formulari.models.autorizzazione_model.AutorizzazioneModel(
                    numero = '', 
                    tipo = null, ),
                attivita = 'R1',
                numero_iscrizione_albo = 'AE/807288',
                id_destinatario = 56,
                dati_firma = rentri_formulari.models.dati_firma_result.DatiFirmaResult(
                    denominazione_firmatario = '', 
                    identificativo_firmatario = '', 
                    data_firma = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    identificativo_utente = '', 
                    credentials_id = '', )
            )
        else:
            return DatiDestinatarioFormularioModel1(
                denominazione = '0',
                codice_fiscale = '01234',
                indirizzo = rentri_formulari.models.indirizzo_model.IndirizzoModel(
                    citta = null, 
                    indirizzo = '0', 
                    civico = '', 
                    cap = '', ),
        )
        """

    def testDatiDestinatarioFormularioModel1(self):
        """Test DatiDestinatarioFormularioModel1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
