# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260211-891
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_formulari.models.i_anagrafica import IAnagrafica  # noqa: E501

class TestIAnagrafica(unittest.TestCase):
    """IAnagrafica unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IAnagrafica:
        """Test IAnagrafica
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IAnagrafica`
        """
        model = IAnagrafica()  # noqa: E501
        if include_optional:
            return IAnagrafica(
                denominazione = '',
                codice_fiscale = ''
            )
        else:
            return IAnagrafica(
        )
        """

    def testIAnagrafica(self):
        """Test IAnagrafica"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
