# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260211-891
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_formulari.models.copia_digitale_model import CopiaDigitaleModel  # noqa: E501

class TestCopiaDigitaleModel(unittest.TestCase):
    """CopiaDigitaleModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CopiaDigitaleModel:
        """Test CopiaDigitaleModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CopiaDigitaleModel`
        """
        model = CopiaDigitaleModel()  # noqa: E501
        if include_optional:
            return CopiaDigitaleModel(
                num_iscr_sito = 'OP0480ZGC880015-CM02170',
                note = '',
                xfir = 'YQ=='
            )
        else:
            return CopiaDigitaleModel(
                num_iscr_sito = 'OP0480ZGC880015-CM02170',
                xfir = 'YQ==',
        )
        """

    def testCopiaDigitaleModel(self):
        """Test CopiaDigitaleModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
