# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260119-862
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class CaratteristichePericolo(str, Enum):
    """
    CaratteristichePericolo
    """

    """
    allowed enum values
    """
    HP01 = 'HP01'
    HP02 = 'HP02'
    HP03 = 'HP03'
    HP04 = 'HP04'
    HP05 = 'HP05'
    HP06 = 'HP06'
    HP07 = 'HP07'
    HP08 = 'HP08'
    HP09 = 'HP09'
    HP10 = 'HP10'
    HP11 = 'HP11'
    HP12 = 'HP12'
    HP13 = 'HP13'
    HP14 = 'HP14'
    HP15 = 'HP15'

    @classmethod
    def from_json(cls, json_str: str) -> CaratteristichePericolo:
        """Create an instance of CaratteristichePericolo from a JSON string"""
        return CaratteristichePericolo(json.loads(json_str))


