# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20250114-507
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, constr

class ComuneModel(BaseModel):
    """
    Comune Italiano  # noqa: E501
    """
    comune_id: constr(strict=True, max_length=6, min_length=1) = Field(default=..., description="Comune ISTAT del comune.  Non vengono accettati codici non corrispondenti a codici ISTAT di comuni italiani.  Vedi API di codifica: <i>GET /codifiche/v1.0/comuni</i>")
    __properties = []

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ComuneModel:
        """Create an instance of ComuneModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ComuneModel:
        """Create an instance of ComuneModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ComuneModel.parse_obj(obj)

        _obj = ComuneModel.parse_obj({
        })
        return _obj


