# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20250114-507
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr, constr

class CopiaCartaceaSoggettoInfo(BaseModel):
    """
    CopiaCartaceaSoggettoInfo
    """
    nazione_id: Optional[constr(strict=True, max_length=2)] = Field(default=None, description="Codice ISO 3166-1 alpha-2 della nazione, in caso di \"IT\" è possibile omettere.  Vengono accettati solo codici previsti dallo standard ISO 3166-1 alpha-2.  Vedi API di codifica: <i>GET /codifiche/v1.0/nazioni</i>  <i>Questo campo viene utilizzato esclusivamente per validare i dati di input in base alla nazione di appartenenza (non viene memorizzato e quindi restituito in output).</i>")
    identificativo: Optional[constr(strict=True, max_length=20, min_length=5)] = Field(default=None, description="Codice fiscale del soggetto ⚠️ Deprecato: utilizzare \"codice_fiscale\"")
    codice_fiscale: constr(strict=True, max_length=20, min_length=5) = Field(default=..., description="Codice fiscale del soggetto.  In base alla nazione (\"nazione_id\") verranno effettuate le seguenti validazioni: - IT: validazioni formale per codice fiscale personale (16 caratteri) o formato partita IVA (11 cifre decimali) - UE: da 5 a 20 caratteri con successiva validazione formale specifica per il paese UE - Extra UE: da 5 a 20 caratteri")
    denominazione: constr(strict=True, min_length=1) = Field(default=..., description="Denominazione del soggetto")
    num_iscr_sito: Optional[StrictStr] = Field(default=None, description="Numero iscrizione unità locale.  Il parametro è opzionale e deve essere fornito al trasportatore dal soggetto.")
    __properties = ["nazione_id", "identificativo", "codice_fiscale", "denominazione", "num_iscr_sito"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CopiaCartaceaSoggettoInfo:
        """Create an instance of CopiaCartaceaSoggettoInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if nazione_id (nullable) is None
        # and __fields_set__ contains the field
        if self.nazione_id is None and "nazione_id" in self.__fields_set__:
            _dict['nazione_id'] = None

        # set to None if identificativo (nullable) is None
        # and __fields_set__ contains the field
        if self.identificativo is None and "identificativo" in self.__fields_set__:
            _dict['identificativo'] = None

        # set to None if num_iscr_sito (nullable) is None
        # and __fields_set__ contains the field
        if self.num_iscr_sito is None and "num_iscr_sito" in self.__fields_set__:
            _dict['num_iscr_sito'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CopiaCartaceaSoggettoInfo:
        """Create an instance of CopiaCartaceaSoggettoInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CopiaCartaceaSoggettoInfo.parse_obj(obj)

        _obj = CopiaCartaceaSoggettoInfo.parse_obj({
            "nazione_id": obj.get("nazione_id"),
            "identificativo": obj.get("identificativo"),
            "codice_fiscale": obj.get("codice_fiscale"),
            "denominazione": obj.get("denominazione"),
            "num_iscr_sito": obj.get("num_iscr_sito")
        })
        return _obj


