# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260119-862
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from rentri_formulari.models.ruolo_conferma_copia_cartacea import RuoloConfermaCopiaCartacea
from typing import Optional, Set
from typing_extensions import Self

class CopiaCartaceaConfermaModel(BaseModel):
    """
    CopiaCartaceaConfermaModel
    """ # noqa: E501
    identificativo: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Identificativo univoco della copia del FIR cartaceo")
    num_iscr_sito: Optional[StrictStr] = Field(default=None, description="Eventuale Numero iscrizione unità locale al quale associare la conferma della copia del FIR cartaceo")
    ruolo: Optional[RuoloConfermaCopiaCartacea] = Field(default=None, description="Ruolo all'interno del FIR del soggetto per cui si effettua l'operazione di conferma di presa visione.")
    respingi: Optional[StrictBool] = Field(default=None, description="Effettua l'operazione di annullamento di una precedente conferma")
    __properties: ClassVar[List[str]] = ["identificativo", "num_iscr_sito", "ruolo", "respingi"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CopiaCartaceaConfermaModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if num_iscr_sito (nullable) is None
        # and model_fields_set contains the field
        if self.num_iscr_sito is None and "num_iscr_sito" in self.model_fields_set:
            _dict['num_iscr_sito'] = None

        # set to None if respingi (nullable) is None
        # and model_fields_set contains the field
        if self.respingi is None and "respingi" in self.model_fields_set:
            _dict['respingi'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CopiaCartaceaConfermaModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "identificativo": obj.get("identificativo"),
            "num_iscr_sito": obj.get("num_iscr_sito"),
            "ruolo": obj.get("ruolo"),
            "respingi": obj.get("respingi")
        })
        return _obj


