# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260211-891
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime

from pydantic import BaseModel, Field, constr

class DatiSostaTecnicaModel(BaseModel):
    """
    DatiSostaTecnicaModel
    """
    luogo_stazionamento: constr(strict=True, max_length=1000, min_length=1) = Field(...)
    data_ora_sospensione: datetime = Field(default=..., description="Formato ISO 8601 UTC")
    data_ora_ripresa: datetime = Field(default=..., description="Formato ISO 8601 UTC")
    __properties = ["luogo_stazionamento", "data_ora_sospensione", "data_ora_ripresa"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DatiSostaTecnicaModel:
        """Create an instance of DatiSostaTecnicaModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DatiSostaTecnicaModel:
        """Create an instance of DatiSostaTecnicaModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DatiSostaTecnicaModel.parse_obj(obj)

        _obj = DatiSostaTecnicaModel.parse_obj({
            "luogo_stazionamento": obj.get("luogo_stazionamento"),
            "data_ora_sospensione": obj.get("data_ora_sospensione"),
            "data_ora_ripresa": obj.get("data_ora_ripresa")
        })
        return _obj


