# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260119-862
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, conlist, constr, validator
from rentri_formulari.models.dati_intermediari_formulario_model import DatiIntermediariFormularioModel
from rentri_formulari.models.dati_partenza_model_destinatario import DatiPartenzaModelDestinatario
from rentri_formulari.models.dati_partenza_model_produttore import DatiPartenzaModelProduttore
from rentri_formulari.models.dati_partenza_model_trasportatori_inner import DatiPartenzaModelTrasportatoriInner
from rentri_formulari.models.dati_rifiuto_model import DatiRifiutoModel
from rentri_formulari.models.dati_trasbordo_parziale_origine_model import DatiTrasbordoParzialeOrigineModel

class DatiPartenzaModel(BaseModel):
    """
    Dati di partenza del formulario  # noqa: E501
    """
    numero_fir: Optional[constr(strict=True)] = Field(default=None, description="Numero di vidimazione da attribuire al nuovo FIR digitale. Qualora non venga specificato, il sistema ne assegnerà uno automaticamente.")
    produttore: Optional[DatiPartenzaModelProduttore] = None
    destinatario: DatiPartenzaModelDestinatario = Field(...)
    trasportatori: conlist(DatiPartenzaModelTrasportatoriInner, min_items=1) = Field(default=..., description="Trasportatori")
    intermediari: Optional[conlist(DatiIntermediariFormularioModel)] = Field(default=None, description="Intermediari")
    rifiuto: DatiRifiutoModel = Field(default=..., description="Caratteristiche del rifiuto")
    trasbordo_parziale_origine: Optional[DatiTrasbordoParzialeOrigineModel] = Field(default=None, description="Dati relativi al trasbordo parziale da cui prende origine il formulario. Il dato deve essere valorizzato solo se il formulario prende origine da un trasbordo parziale. Se il dato viene valorizzato, la proprietà \"produttore\" non deve essere valorizzata.")
    annotazioni: Optional[constr(strict=True, max_length=10000)] = Field(default=None, description="Annotazioni")
    __properties = ["numero_fir", "produttore", "destinatario", "trasportatori", "intermediari", "rifiuto", "trasbordo_parziale_origine", "annotazioni"]

    @validator('numero_fir')
    def numero_fir_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^([BCDFGHJKLMNPQRSTVWXYZ]{4,6})[ 	-\/_]*([0-9]+)[ 	-\/_]*([BCDFGHJKLMNPQRSTVWXYZ]{1,2})$", value):
            raise ValueError(r"must validate the regular expression /^([BCDFGHJKLMNPQRSTVWXYZ]{4,6})[ 	-\/_]*([0-9]+)[ 	-\/_]*([BCDFGHJKLMNPQRSTVWXYZ]{1,2})$/")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DatiPartenzaModel:
        """Create an instance of DatiPartenzaModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of produttore
        if self.produttore:
            _dict['produttore'] = self.produttore.to_dict()
        # override the default output from pydantic by calling `to_dict()` of destinatario
        if self.destinatario:
            _dict['destinatario'] = self.destinatario.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in trasportatori (list)
        _items = []
        if self.trasportatori:
            for _item in self.trasportatori:
                if _item:
                    _items.append(_item.to_dict())
            _dict['trasportatori'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in intermediari (list)
        _items = []
        if self.intermediari:
            for _item in self.intermediari:
                if _item:
                    _items.append(_item.to_dict())
            _dict['intermediari'] = _items
        # override the default output from pydantic by calling `to_dict()` of rifiuto
        if self.rifiuto:
            _dict['rifiuto'] = self.rifiuto.to_dict()
        # override the default output from pydantic by calling `to_dict()` of trasbordo_parziale_origine
        if self.trasbordo_parziale_origine:
            _dict['trasbordo_parziale_origine'] = self.trasbordo_parziale_origine.to_dict()
        # set to None if numero_fir (nullable) is None
        # and __fields_set__ contains the field
        if self.numero_fir is None and "numero_fir" in self.__fields_set__:
            _dict['numero_fir'] = None

        # set to None if produttore (nullable) is None
        # and __fields_set__ contains the field
        if self.produttore is None and "produttore" in self.__fields_set__:
            _dict['produttore'] = None

        # set to None if intermediari (nullable) is None
        # and __fields_set__ contains the field
        if self.intermediari is None and "intermediari" in self.__fields_set__:
            _dict['intermediari'] = None

        # set to None if trasbordo_parziale_origine (nullable) is None
        # and __fields_set__ contains the field
        if self.trasbordo_parziale_origine is None and "trasbordo_parziale_origine" in self.__fields_set__:
            _dict['trasbordo_parziale_origine'] = None

        # set to None if annotazioni (nullable) is None
        # and __fields_set__ contains the field
        if self.annotazioni is None and "annotazioni" in self.__fields_set__:
            _dict['annotazioni'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DatiPartenzaModel:
        """Create an instance of DatiPartenzaModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DatiPartenzaModel.parse_obj(obj)

        _obj = DatiPartenzaModel.parse_obj({
            "numero_fir": obj.get("numero_fir"),
            "produttore": DatiPartenzaModelProduttore.from_dict(obj.get("produttore")) if obj.get("produttore") is not None else None,
            "destinatario": DatiPartenzaModelDestinatario.from_dict(obj.get("destinatario")) if obj.get("destinatario") is not None else None,
            "trasportatori": [DatiPartenzaModelTrasportatoriInner.from_dict(_item) for _item in obj.get("trasportatori")] if obj.get("trasportatori") is not None else None,
            "intermediari": [DatiIntermediariFormularioModel.from_dict(_item) for _item in obj.get("intermediari")] if obj.get("intermediari") is not None else None,
            "rifiuto": DatiRifiutoModel.from_dict(obj.get("rifiuto")) if obj.get("rifiuto") is not None else None,
            "trasbordo_parziale_origine": DatiTrasbordoParzialeOrigineModel.from_dict(obj.get("trasbordo_parziale_origine")) if obj.get("trasbordo_parziale_origine") is not None else None,
            "annotazioni": obj.get("annotazioni")
        })
        return _obj


