# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260211-891
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from rentri_formulari.models.conducente_model import ConducenteModel
from typing import Optional, Set
from typing_extensions import Self

class DatiTrasportoTerrestreModel(BaseModel):
    """
    DatiTrasportoTerrestreModel
    """ # noqa: E501
    data_ora_inizio_trasporto: datetime = Field(description="Data e ora inizio trasporto (formato ISO 8601 UTC)")
    annotazioni: Optional[Annotated[str, Field(strict=True, max_length=10000)]] = Field(default=None, description="Annotazioni")
    conducente: ConducenteModel = Field(description="Conducente")
    targa_automezzo: Optional[Annotated[str, Field(strict=True, max_length=10)]] = Field(default=None, description="Targa automezzo.  Il dato è necessario se non si indica una targa per il rimorchio")
    targa_rimorchio: Optional[Annotated[str, Field(strict=True, max_length=10)]] = Field(default=None, description="Targa rimorchio")
    percorso: Optional[Annotated[str, Field(strict=True, max_length=250)]] = Field(default=None, description="Percorso (se diverso dal più breve)")
    presa_in_carico_rimorchio_precedente: Optional[StrictBool] = Field(default=None, description="Significativo solo per i trasporti successivi al primo")
    __properties: ClassVar[List[str]] = ["data_ora_inizio_trasporto", "annotazioni", "conducente", "targa_automezzo", "targa_rimorchio", "percorso", "presa_in_carico_rimorchio_precedente"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DatiTrasportoTerrestreModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of conducente
        if self.conducente:
            _dict['conducente'] = self.conducente.to_dict()
        # set to None if annotazioni (nullable) is None
        # and model_fields_set contains the field
        if self.annotazioni is None and "annotazioni" in self.model_fields_set:
            _dict['annotazioni'] = None

        # set to None if targa_automezzo (nullable) is None
        # and model_fields_set contains the field
        if self.targa_automezzo is None and "targa_automezzo" in self.model_fields_set:
            _dict['targa_automezzo'] = None

        # set to None if targa_rimorchio (nullable) is None
        # and model_fields_set contains the field
        if self.targa_rimorchio is None and "targa_rimorchio" in self.model_fields_set:
            _dict['targa_rimorchio'] = None

        # set to None if percorso (nullable) is None
        # and model_fields_set contains the field
        if self.percorso is None and "percorso" in self.model_fields_set:
            _dict['percorso'] = None

        # set to None if presa_in_carico_rimorchio_precedente (nullable) is None
        # and model_fields_set contains the field
        if self.presa_in_carico_rimorchio_precedente is None and "presa_in_carico_rimorchio_precedente" in self.model_fields_set:
            _dict['presa_in_carico_rimorchio_precedente'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DatiTrasportoTerrestreModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "data_ora_inizio_trasporto": obj.get("data_ora_inizio_trasporto"),
            "annotazioni": obj.get("annotazioni"),
            "conducente": ConducenteModel.from_dict(obj["conducente"]) if obj.get("conducente") is not None else None,
            "targa_automezzo": obj.get("targa_automezzo"),
            "targa_rimorchio": obj.get("targa_rimorchio"),
            "percorso": obj.get("percorso"),
            "presa_in_carico_rimorchio_precedente": obj.get("presa_in_carico_rimorchio_precedente")
        })
        return _obj


