# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260211-891
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr
from rentri_formulari.models.proprieta_dati_notifica_push_carica_copia_digitale_model import ProprietaDatiNotificaPushCaricaCopiaDigitaleModel

class DatiNotificaPushCaricaCopiaDigitaleModel(BaseModel):
    """
    Dati della notifica push per il caricamento della copia digitale  # noqa: E501
    """
    proprieta: Optional[ProprietaDatiNotificaPushCaricaCopiaDigitaleModel] = Field(default=None, description="Proprietà specifiche della notifica")
    tipo: Optional[StrictStr] = Field(default=None, description="Tipo di notifica")
    __properties = ["proprieta", "tipo"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DatiNotificaPushCaricaCopiaDigitaleModel:
        """Create an instance of DatiNotificaPushCaricaCopiaDigitaleModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of proprieta
        if self.proprieta:
            _dict['proprieta'] = self.proprieta.to_dict()
        # set to None if proprieta (nullable) is None
        # and __fields_set__ contains the field
        if self.proprieta is None and "proprieta" in self.__fields_set__:
            _dict['proprieta'] = None

        # set to None if tipo (nullable) is None
        # and __fields_set__ contains the field
        if self.tipo is None and "tipo" in self.__fields_set__:
            _dict['tipo'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DatiNotificaPushCaricaCopiaDigitaleModel:
        """Create an instance of DatiNotificaPushCaricaCopiaDigitaleModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DatiNotificaPushCaricaCopiaDigitaleModel.parse_obj(obj)

        _obj = DatiNotificaPushCaricaCopiaDigitaleModel.parse_obj({
            "proprieta": ProprietaDatiNotificaPushCaricaCopiaDigitaleModel.from_dict(obj.get("proprieta")) if obj.get("proprieta") is not None else None,
            "tipo": obj.get("tipo")
        })
        return _obj


