# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260119-862
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class DatiTrasportoFerroviarioModel(BaseModel):
    """
    DatiTrasportoFerroviarioModel
    """ # noqa: E501
    treno: Annotated[str, Field(min_length=1, strict=True, max_length=50)]
    rid: Optional[StrictBool] = None
    tratta: Optional[Annotated[str, Field(strict=True, max_length=50)]] = None
    data_ora_inizio_trasporto: datetime = Field(description="Data e ora inizio trasporto (formato ISO 8601 UTC)")
    annotazioni: Optional[Annotated[str, Field(strict=True, max_length=10000)]] = Field(default=None, description="Annotazioni")
    __properties: ClassVar[List[str]] = ["data_ora_inizio_trasporto", "annotazioni"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DatiTrasportoFerroviarioModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if annotazioni (nullable) is None
        # and model_fields_set contains the field
        if self.annotazioni is None and "annotazioni" in self.model_fields_set:
            _dict['annotazioni'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DatiTrasportoFerroviarioModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "treno": obj.get('treno'),
            "rid": obj.get('rid'),
            "tratta": obj.get('tratta'),
            "data_ora_inizio_trasporto": obj.get("data_ora_inizio_trasporto"),
            "annotazioni": obj.get("annotazioni")
        })
        return _obj


