# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20250114-507
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictInt
from rentri_formulari.models.dati_trasportatore_trasmissione_model import DatiTrasportatoreTrasmissioneModel
from rentri_formulari.models.dati_trasporto_trasmissione_base_model1 import DatiTrasportoTrasmissioneBaseModel1

class DatiTrasbordoTotaleTrasmissioneModel(BaseModel):
    """
    DatiTrasbordoTotaleTrasmissioneModel
    """
    id_trasportatore_trasbordo: StrictInt = Field(default=..., description="Id del trasportatore definito all'interno dei dati che vengono trasmessi a cui è riferito il trasbordo")
    trasportatore: DatiTrasportatoreTrasmissioneModel = Field(...)
    presa_in_carico: DatiTrasportoTrasmissioneBaseModel1 = Field(...)
    __properties = ["id_trasportatore_trasbordo", "trasportatore", "presa_in_carico"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DatiTrasbordoTotaleTrasmissioneModel:
        """Create an instance of DatiTrasbordoTotaleTrasmissioneModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of trasportatore
        if self.trasportatore:
            _dict['trasportatore'] = self.trasportatore.to_dict()
        # override the default output from pydantic by calling `to_dict()` of presa_in_carico
        if self.presa_in_carico:
            _dict['presa_in_carico'] = self.presa_in_carico.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DatiTrasbordoTotaleTrasmissioneModel:
        """Create an instance of DatiTrasbordoTotaleTrasmissioneModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DatiTrasbordoTotaleTrasmissioneModel.parse_obj(obj)

        _obj = DatiTrasbordoTotaleTrasmissioneModel.parse_obj({
            "id_trasportatore_trasbordo": obj.get("id_trasportatore_trasbordo"),
            "trasportatore": DatiTrasportatoreTrasmissioneModel.from_dict(obj.get("trasportatore")) if obj.get("trasportatore") is not None else None,
            "presa_in_carico": DatiTrasportoTrasmissioneBaseModel1.from_dict(obj.get("presa_in_carico")) if obj.get("presa_in_carico") is not None else None
        })
        return _obj


