# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260119-862
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from rentri_formulari.models.tipo_trasporto import TipoTrasporto
from typing import Optional, Set
from typing_extensions import Self

class DatiTrasportatoreFormularioModel(BaseModel):
    """
    Dati trasportatore
    """ # noqa: E501
    denominazione: Annotated[str, Field(min_length=1, strict=True, max_length=1000)] = Field(description="Denominazione del soggetto")
    codice_fiscale: Annotated[str, Field(min_length=5, strict=True, max_length=20)] = Field(description="Codice fiscale del soggetto. In base alla nazione (\"nazione_id\") verranno effettuate le seguenti validazioni: - IT: validazioni formale per codice fiscale personale (16 caratteri) o formato partita IVA (11 cifre decimali) - UE: da 5 a 20 caratteri con successiva validazione formale specifica per il paese UE - Extra UE: da 5 a 20 caratteri")
    nazione_id: Optional[Annotated[str, Field(strict=True, max_length=2)]] = Field(default=None, description="Codice ISO 3166-1 alpha-2 della nazione, in caso di \"IT\" è possibile omettere.  Vengono accettati solo codici previsti dallo standard ISO 3166-1 alpha-2.  Vedi API di codifica: <i>GET /codifiche/v1.0/nazioni</i>")
    tipo_trasporto: TipoTrasporto
    numero_iscrizione_albo: Optional[Annotated[str, Field(strict=True, max_length=10)]] = Field(default=None, description="Iscrizione Albo")
    __properties: ClassVar[List[str]] = ["tipo_trasporto", "numero_iscrizione_albo"]

    @field_validator('numero_iscrizione_albo')
    def numero_iscrizione_albo_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^([A-Za-z]{2})\/([0-9]{6})$", value):
            raise ValueError(r"must validate the regular expression /^([A-Za-z]{2})\/([0-9]{6})$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DatiTrasportatoreFormularioModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if numero_iscrizione_albo (nullable) is None
        # and model_fields_set contains the field
        if self.numero_iscrizione_albo is None and "numero_iscrizione_albo" in self.model_fields_set:
            _dict['numero_iscrizione_albo'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DatiTrasportatoreFormularioModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "denominazione": obj.get('denominazione'),
            "codice_fiscale": obj.get('codice_fiscale'),
            "nazione_id": obj.get('nazione_id'),
            "tipo_trasporto": obj.get("tipo_trasporto"),
            "numero_iscrizione_albo": obj.get("numero_iscrizione_albo")
        })
        return _obj


