# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260211-891
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field
from rentri_formulari.models.dati_partenza_model_trasportatori_inner import DatiPartenzaModelTrasportatoriInner
from rentri_formulari.models.dati_trasporto_terrestre_model import DatiTrasportoTerrestreModel

class DatiTrasbordoTotaleModel(BaseModel):
    """
    DatiTrasbordoTotaleModel
    """
    trasportatore: DatiPartenzaModelTrasportatoriInner = Field(...)
    presa_in_carico: DatiTrasportoTerrestreModel = Field(default=..., description="Dati del trasporto terrestre")
    __properties = ["trasportatore", "presa_in_carico"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DatiTrasbordoTotaleModel:
        """Create an instance of DatiTrasbordoTotaleModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of trasportatore
        if self.trasportatore:
            _dict['trasportatore'] = self.trasportatore.to_dict()
        # override the default output from pydantic by calling `to_dict()` of presa_in_carico
        if self.presa_in_carico:
            _dict['presa_in_carico'] = self.presa_in_carico.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DatiTrasbordoTotaleModel:
        """Create an instance of DatiTrasbordoTotaleModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DatiTrasbordoTotaleModel.parse_obj(obj)

        _obj = DatiTrasbordoTotaleModel.parse_obj({
            "trasportatore": DatiPartenzaModelTrasportatoriInner.from_dict(obj.get("trasportatore")) if obj.get("trasportatore") is not None else None,
            "presa_in_carico": DatiTrasportoTerrestreModel.from_dict(obj.get("presa_in_carico")) if obj.get("presa_in_carico") is not None else None
        })
        return _obj


