# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260119-862
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from rentri_formulari.models.dati_trasportatore_trasmissione_model import DatiTrasportatoreTrasmissioneModel
from rentri_formulari.models.dati_trasporto_trasmissione_base_model1 import DatiTrasportoTrasmissioneBaseModel1
from typing import Optional, Set
from typing_extensions import Self

class DatiTrasbordoTotaleTrasmissioneModel(BaseModel):
    """
    DatiTrasbordoTotaleTrasmissioneModel
    """ # noqa: E501
    trasportatore_id: Annotated[int, Field(le=255, strict=True, ge=1)] = Field(description="Id del trasportatore definito all'interno dei dati che vengono trasmessi a cui è riferito il trasbordo")
    id_trasportatore_trasbordo: Optional[StrictInt] = Field(default=None, description="Id del trasportatore definito all'interno dei dati che vengono trasmessi a cui è riferito il trasbordo       ⚠️ Deprecato: utilizzare \"trasportatore_id\"")
    trasportatore: DatiTrasportatoreTrasmissioneModel
    presa_in_carico: DatiTrasportoTrasmissioneBaseModel1
    __properties: ClassVar[List[str]] = ["trasportatore_id", "id_trasportatore_trasbordo", "trasportatore", "presa_in_carico"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DatiTrasbordoTotaleTrasmissioneModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of trasportatore
        if self.trasportatore:
            _dict['trasportatore'] = self.trasportatore.to_dict()
        # override the default output from pydantic by calling `to_dict()` of presa_in_carico
        if self.presa_in_carico:
            _dict['presa_in_carico'] = self.presa_in_carico.to_dict()
        # set to None if id_trasportatore_trasbordo (nullable) is None
        # and model_fields_set contains the field
        if self.id_trasportatore_trasbordo is None and "id_trasportatore_trasbordo" in self.model_fields_set:
            _dict['id_trasportatore_trasbordo'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DatiTrasbordoTotaleTrasmissioneModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "trasportatore_id": obj.get("trasportatore_id"),
            "id_trasportatore_trasbordo": obj.get("id_trasportatore_trasbordo"),
            "trasportatore": DatiTrasportatoreTrasmissioneModel.from_dict(obj["trasportatore"]) if obj.get("trasportatore") is not None else None,
            "presa_in_carico": DatiTrasportoTrasmissioneBaseModel1.from_dict(obj["presa_in_carico"]) if obj.get("presa_in_carico") is not None else None
        })
        return _obj


