# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20250114-507
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, constr, validator

class DatiTrasportatoreTrasbordoModel(BaseModel):
    """
    Dati trasportatore per il trasbordo parziale  # noqa: E501
    """
    nazione_id: Optional[constr(strict=True, max_length=2)] = Field(default=None, description="Codice ISO 3166-1 alpha-2 della nazione, in caso di \"IT\" è possibile omettere.  Vengono accettati solo codici previsti dallo standard ISO 3166-1 alpha-2.  Vedi API di codifica: <i>GET /codifiche/v1.0/nazioni</i>")
    denominazione: constr(strict=True, min_length=1) = Field(default=..., description="Denominazione del soggetto")
    codice_fiscale: constr(strict=True, max_length=20, min_length=5) = Field(default=..., description="Codice fiscale del soggetto. In base alla nazione (\"nazione_id\") verranno effettuate le seguenti validazioni: - IT: validazioni formale per codice fiscale personale (16 caratteri) o formato partita IVA (11 cifre decimali) - UE: da 5 a 20 caratteri con successiva validazione formale specifica per il paese UE - Extra UE: da 5 a 20 caratteri")
    numero_iscrizione_albo: Optional[constr(strict=True)] = Field(default=None, description="Iscrizione Albo")
    __properties = ["nazione_id", "denominazione", "codice_fiscale", "numero_iscrizione_albo"]

    @validator('numero_iscrizione_albo')
    def numero_iscrizione_albo_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^([A-Za-z]{2})\/([0-9]{6})$", value):
            raise ValueError(r"must validate the regular expression /^([A-Za-z]{2})\/([0-9]{6})$/")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DatiTrasportatoreTrasbordoModel:
        """Create an instance of DatiTrasportatoreTrasbordoModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if nazione_id (nullable) is None
        # and __fields_set__ contains the field
        if self.nazione_id is None and "nazione_id" in self.__fields_set__:
            _dict['nazione_id'] = None

        # set to None if numero_iscrizione_albo (nullable) is None
        # and __fields_set__ contains the field
        if self.numero_iscrizione_albo is None and "numero_iscrizione_albo" in self.__fields_set__:
            _dict['numero_iscrizione_albo'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DatiTrasportatoreTrasbordoModel:
        """Create an instance of DatiTrasportatoreTrasbordoModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DatiTrasportatoreTrasbordoModel.parse_obj(obj)

        _obj = DatiTrasportatoreTrasbordoModel.parse_obj({
            "nazione_id": obj.get("nazione_id"),
            "denominazione": obj.get("denominazione"),
            "codice_fiscale": obj.get("codice_fiscale"),
            "numero_iscrizione_albo": obj.get("numero_iscrizione_albo")
        })
        return _obj


