# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20250114-507
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from rentri_formulari.models.dati_trasporto_ferroviario_result_model import DatiTrasportoFerroviarioResultModel
from rentri_formulari.models.dati_trasporto_marittimo_result_model import DatiTrasportoMarittimoResultModel
from rentri_formulari.models.dati_trasporto_terrestre_result_model import DatiTrasportoTerrestreResultModel
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

DETTAGLIOFORMULARIODATITRASPORTOINNER_ONE_OF_SCHEMAS = ["DatiTrasportoFerroviarioResultModel", "DatiTrasportoMarittimoResultModel", "DatiTrasportoTerrestreResultModel"]

class DettaglioFormularioDatiTrasportoInner(BaseModel):
    """
    Dati del trasporto base
    """
    # data type: DatiTrasportoTerrestreResultModel
    oneof_schema_1_validator: Optional[DatiTrasportoTerrestreResultModel] = None
    # data type: DatiTrasportoMarittimoResultModel
    oneof_schema_2_validator: Optional[DatiTrasportoMarittimoResultModel] = None
    # data type: DatiTrasportoFerroviarioResultModel
    oneof_schema_3_validator: Optional[DatiTrasportoFerroviarioResultModel] = None
    actual_instance: Optional[Union[DatiTrasportoFerroviarioResultModel, DatiTrasportoMarittimoResultModel, DatiTrasportoTerrestreResultModel]] = None
    one_of_schemas: Set[str] = { "DatiTrasportoFerroviarioResultModel", "DatiTrasportoMarittimoResultModel", "DatiTrasportoTerrestreResultModel" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = DettaglioFormularioDatiTrasportoInner.model_construct()
        error_messages = []
        match = 0
        # validate data type: DatiTrasportoTerrestreResultModel
        if not isinstance(v, DatiTrasportoTerrestreResultModel):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DatiTrasportoTerrestreResultModel`")
        else:
            match += 1
        # validate data type: DatiTrasportoMarittimoResultModel
        if not isinstance(v, DatiTrasportoMarittimoResultModel):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DatiTrasportoMarittimoResultModel`")
        else:
            match += 1
        # validate data type: DatiTrasportoFerroviarioResultModel
        if not isinstance(v, DatiTrasportoFerroviarioResultModel):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DatiTrasportoFerroviarioResultModel`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in DettaglioFormularioDatiTrasportoInner with oneOf schemas: DatiTrasportoFerroviarioResultModel, DatiTrasportoMarittimoResultModel, DatiTrasportoTerrestreResultModel. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in DettaglioFormularioDatiTrasportoInner with oneOf schemas: DatiTrasportoFerroviarioResultModel, DatiTrasportoMarittimoResultModel, DatiTrasportoTerrestreResultModel. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into DatiTrasportoTerrestreResultModel
        try:
            instance.actual_instance = DatiTrasportoTerrestreResultModel.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DatiTrasportoMarittimoResultModel
        try:
            instance.actual_instance = DatiTrasportoMarittimoResultModel.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DatiTrasportoFerroviarioResultModel
        try:
            instance.actual_instance = DatiTrasportoFerroviarioResultModel.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into DettaglioFormularioDatiTrasportoInner with oneOf schemas: DatiTrasportoFerroviarioResultModel, DatiTrasportoMarittimoResultModel, DatiTrasportoTerrestreResultModel. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into DettaglioFormularioDatiTrasportoInner with oneOf schemas: DatiTrasportoFerroviarioResultModel, DatiTrasportoMarittimoResultModel, DatiTrasportoTerrestreResultModel. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], DatiTrasportoFerroviarioResultModel, DatiTrasportoMarittimoResultModel, DatiTrasportoTerrestreResultModel]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


