# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260211-891
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictBytes, StrictStr

class DownloadableBaseResponse(BaseModel):
    """
    DownloadableBaseResponse
    """
    nome_file: Optional[StrictStr] = Field(default=None, description="Nome del file")
    mime: Optional[StrictStr] = Field(default=None, description="Tipo MIME del file")
    content: Optional[Union[StrictBytes, StrictStr]] = Field(default=None, description="Contenuto del file")
    __properties = ["nome_file", "mime", "content"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DownloadableBaseResponse:
        """Create an instance of DownloadableBaseResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if nome_file (nullable) is None
        # and __fields_set__ contains the field
        if self.nome_file is None and "nome_file" in self.__fields_set__:
            _dict['nome_file'] = None

        # set to None if mime (nullable) is None
        # and __fields_set__ contains the field
        if self.mime is None and "mime" in self.__fields_set__:
            _dict['mime'] = None

        # set to None if content (nullable) is None
        # and __fields_set__ contains the field
        if self.content is None and "content" in self.__fields_set__:
            _dict['content'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DownloadableBaseResponse:
        """Create an instance of DownloadableBaseResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DownloadableBaseResponse.parse_obj(obj)

        _obj = DownloadableBaseResponse.parse_obj({
            "nome_file": obj.get("nome_file"),
            "mime": obj.get("mime"),
            "content": obj.get("content")
        })
        return _obj


