# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260119-862
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, Dict, List, Optional
from rentri_formulari.models.esito_add_allegato_model import EsitoAddAllegatoModel
from rentri_formulari.models.esito_carica_copia_cartacea_model import EsitoCaricaCopiaCartaceaModel
from rentri_formulari.models.esito_carica_copia_digitale_model import EsitoCaricaCopiaDigitaleModel
from rentri_formulari.models.esito_estrai_dati_xfir_model import EsitoEstraiDatiXfirModel
from rentri_formulari.models.esito_get_hash_per_firma_model import EsitoGetHashPerFirmaModel
from rentri_formulari.models.esito_nuovo_formulario_model import EsitoNuovoFormularioModel
from rentri_formulari.models.esito_upload_xfir_model import EsitoUploadXfirModel
from rentri_formulari.models.esito_valida_xfir_model import EsitoValidaXfirModel
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

ESITOFORMULARIOMODELESITO_ONE_OF_SCHEMAS = ["EsitoAddAllegatoModel", "EsitoCaricaCopiaCartaceaModel", "EsitoCaricaCopiaDigitaleModel", "EsitoEstraiDatiXfirModel", "EsitoGetHashPerFirmaModel", "EsitoNuovoFormularioModel", "EsitoUploadXfirModel", "EsitoValidaXfirModel", "object"]

class EsitoFormularioModelEsito(BaseModel):
    """
    Esito
    """
    # data type: object
    oneof_schema_1_validator: Optional[Dict[str, Any]] = None
    # data type: EsitoNuovoFormularioModel
    oneof_schema_2_validator: Optional[EsitoNuovoFormularioModel] = None
    # data type: EsitoGetHashPerFirmaModel
    oneof_schema_3_validator: Optional[EsitoGetHashPerFirmaModel] = None
    # data type: EsitoAddAllegatoModel
    oneof_schema_4_validator: Optional[EsitoAddAllegatoModel] = None
    # data type: EsitoValidaXfirModel
    oneof_schema_5_validator: Optional[EsitoValidaXfirModel] = None
    # data type: EsitoUploadXfirModel
    oneof_schema_6_validator: Optional[EsitoUploadXfirModel] = None
    # data type: EsitoCaricaCopiaCartaceaModel
    oneof_schema_7_validator: Optional[EsitoCaricaCopiaCartaceaModel] = None
    # data type: EsitoCaricaCopiaDigitaleModel
    oneof_schema_8_validator: Optional[EsitoCaricaCopiaDigitaleModel] = None
    # data type: EsitoEstraiDatiXfirModel
    oneof_schema_9_validator: Optional[EsitoEstraiDatiXfirModel] = None
    actual_instance: Optional[Union[EsitoAddAllegatoModel, EsitoCaricaCopiaCartaceaModel, EsitoCaricaCopiaDigitaleModel, EsitoEstraiDatiXfirModel, EsitoGetHashPerFirmaModel, EsitoNuovoFormularioModel, EsitoUploadXfirModel, EsitoValidaXfirModel, object]] = None
    one_of_schemas: Set[str] = { "EsitoAddAllegatoModel", "EsitoCaricaCopiaCartaceaModel", "EsitoCaricaCopiaDigitaleModel", "EsitoEstraiDatiXfirModel", "EsitoGetHashPerFirmaModel", "EsitoNuovoFormularioModel", "EsitoUploadXfirModel", "EsitoValidaXfirModel", "object" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        if v is None:
            return v

        instance = EsitoFormularioModelEsito.model_construct()
        error_messages = []
        match = 0
        # validate data type: object
        try:
            instance.oneof_schema_1_validator = v
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: EsitoNuovoFormularioModel
        if not isinstance(v, EsitoNuovoFormularioModel):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EsitoNuovoFormularioModel`")
        else:
            match += 1
        # validate data type: EsitoGetHashPerFirmaModel
        if not isinstance(v, EsitoGetHashPerFirmaModel):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EsitoGetHashPerFirmaModel`")
        else:
            match += 1
        # validate data type: EsitoAddAllegatoModel
        if not isinstance(v, EsitoAddAllegatoModel):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EsitoAddAllegatoModel`")
        else:
            match += 1
        # validate data type: EsitoValidaXfirModel
        if not isinstance(v, EsitoValidaXfirModel):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EsitoValidaXfirModel`")
        else:
            match += 1
        # validate data type: EsitoUploadXfirModel
        if not isinstance(v, EsitoUploadXfirModel):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EsitoUploadXfirModel`")
        else:
            match += 1
        # validate data type: EsitoCaricaCopiaCartaceaModel
        if not isinstance(v, EsitoCaricaCopiaCartaceaModel):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EsitoCaricaCopiaCartaceaModel`")
        else:
            match += 1
        # validate data type: EsitoCaricaCopiaDigitaleModel
        if not isinstance(v, EsitoCaricaCopiaDigitaleModel):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EsitoCaricaCopiaDigitaleModel`")
        else:
            match += 1
        # validate data type: EsitoEstraiDatiXfirModel
        if not isinstance(v, EsitoEstraiDatiXfirModel):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EsitoEstraiDatiXfirModel`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in EsitoFormularioModelEsito with oneOf schemas: EsitoAddAllegatoModel, EsitoCaricaCopiaCartaceaModel, EsitoCaricaCopiaDigitaleModel, EsitoEstraiDatiXfirModel, EsitoGetHashPerFirmaModel, EsitoNuovoFormularioModel, EsitoUploadXfirModel, EsitoValidaXfirModel, object. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in EsitoFormularioModelEsito with oneOf schemas: EsitoAddAllegatoModel, EsitoCaricaCopiaCartaceaModel, EsitoCaricaCopiaDigitaleModel, EsitoEstraiDatiXfirModel, EsitoGetHashPerFirmaModel, EsitoNuovoFormularioModel, EsitoUploadXfirModel, EsitoValidaXfirModel, object. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: Optional[str]) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        if json_str is None:
            return instance

        error_messages = []
        match = 0

        # deserialize data into object
        try:
            # validation
            instance.oneof_schema_1_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.oneof_schema_1_validator
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match == 1:
            return instance

        # deserialize data into EsitoNuovoFormularioModel
        try:
            instance.actual_instance = EsitoNuovoFormularioModel.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into EsitoGetHashPerFirmaModel
        try:
            instance.actual_instance = EsitoGetHashPerFirmaModel.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into EsitoAddAllegatoModel
        try:
            instance.actual_instance = EsitoAddAllegatoModel.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into EsitoValidaXfirModel
        try:
            instance.actual_instance = EsitoValidaXfirModel.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into EsitoUploadXfirModel
        try:
            instance.actual_instance = EsitoUploadXfirModel.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into EsitoCaricaCopiaCartaceaModel
        try:
            instance.actual_instance = EsitoCaricaCopiaCartaceaModel.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into EsitoCaricaCopiaDigitaleModel
        try:
            instance.actual_instance = EsitoCaricaCopiaDigitaleModel.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into EsitoEstraiDatiXfirModel
        try:
            instance.actual_instance = EsitoEstraiDatiXfirModel.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into EsitoFormularioModelEsito with oneOf schemas: EsitoAddAllegatoModel, EsitoCaricaCopiaCartaceaModel, EsitoCaricaCopiaDigitaleModel, EsitoEstraiDatiXfirModel, EsitoGetHashPerFirmaModel, EsitoNuovoFormularioModel, EsitoUploadXfirModel, EsitoValidaXfirModel, object. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into EsitoFormularioModelEsito with oneOf schemas: EsitoAddAllegatoModel, EsitoCaricaCopiaCartaceaModel, EsitoCaricaCopiaDigitaleModel, EsitoEstraiDatiXfirModel, EsitoGetHashPerFirmaModel, EsitoNuovoFormularioModel, EsitoUploadXfirModel, EsitoValidaXfirModel, object. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], EsitoAddAllegatoModel, EsitoCaricaCopiaCartaceaModel, EsitoCaricaCopiaDigitaleModel, EsitoEstraiDatiXfirModel, EsitoGetHashPerFirmaModel, EsitoNuovoFormularioModel, EsitoUploadXfirModel, EsitoValidaXfirModel, object]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


