# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20250114-507
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, conbytes, constr

class FirmaModel(BaseModel):
    """
    FirmaModel
    """
    certificato: constr(strict=True, min_length=1) = Field(default=..., description="Certificato in base64")
    token: constr(strict=True, min_length=1) = Field(default=..., description="Stringa in base64 contenente il token restituito dalla chiamata con cui si è ottenuto l'hash che si è firmato. Deve essere restituita assieme alla firma nella procedura di acquisizione")
    firma: Union[conbytes(strict=True, min_length=1), constr(strict=True, min_length=1)] = Field(default=..., description="Stringa in base64 contenente l'array di byte che costituisce la firma dell'hash")
    identificativo_utente: Optional[constr(strict=True, max_length=255)] = Field(default=None, description="Identificativo dell'utente, contestuale all'ambiente di utilizzo del chiamante, al quale far risalire l'operazione di firma")
    __properties = ["certificato", "token", "firma", "identificativo_utente"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> FirmaModel:
        """Create an instance of FirmaModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if identificativo_utente (nullable) is None
        # and __fields_set__ contains the field
        if self.identificativo_utente is None and "identificativo_utente" in self.__fields_set__:
            _dict['identificativo_utente'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> FirmaModel:
        """Create an instance of FirmaModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return FirmaModel.parse_obj(obj)

        _obj = FirmaModel.parse_obj({
            "certificato": obj.get("certificato"),
            "token": obj.get("token"),
            "firma": obj.get("firma"),
            "identificativo_utente": obj.get("identificativo_utente")
        })
        return _obj


