# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260211-891
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, constr

class NormativaADRModel(BaseModel):
    """
    Normativa ADR  # noqa: E501
    """
    numero_onu: Optional[constr(strict=True, max_length=20)] = Field(default=None, description="Numero ONU")
    classe: Optional[constr(strict=True, max_length=20)] = None
    note: Optional[constr(strict=True, max_length=500)] = Field(default=None, description="Note ADR")
    __properties = ["numero_onu", "classe", "note"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> NormativaADRModel:
        """Create an instance of NormativaADRModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if numero_onu (nullable) is None
        # and __fields_set__ contains the field
        if self.numero_onu is None and "numero_onu" in self.__fields_set__:
            _dict['numero_onu'] = None

        # set to None if classe (nullable) is None
        # and __fields_set__ contains the field
        if self.classe is None and "classe" in self.__fields_set__:
            _dict['classe'] = None

        # set to None if note (nullable) is None
        # and __fields_set__ contains the field
        if self.note is None and "note" in self.__fields_set__:
            _dict['note'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> NormativaADRModel:
        """Create an instance of NormativaADRModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return NormativaADRModel.parse_obj(obj)

        _obj = NormativaADRModel.parse_obj({
            "numero_onu": obj.get("numero_onu"),
            "classe": obj.get("classe"),
            "note": obj.get("note")
        })
        return _obj


