# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260119-862
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401

from typing import Any, List, Optional
from pydantic import BaseModel, Field, StrictStr, ValidationError, validator
from rentri_formulari.models.dati_trasporto_ferroviario_model import DatiTrasportoFerroviarioModel
from rentri_formulari.models.dati_trasporto_marittimo_model import DatiTrasportoMarittimoModel
from rentri_formulari.models.dati_trasporto_terrestre_model import DatiTrasportoTerrestreModel
from typing import Union, Any, List, TYPE_CHECKING
from pydantic import StrictStr, Field

NUOVOFORMULARIOMODELDATITRASPORTOPARTENZA_ONE_OF_SCHEMAS = ["DatiTrasportoFerroviarioModel", "DatiTrasportoMarittimoModel", "DatiTrasportoTerrestreModel"]

class NuovoFormularioModelDatiTrasportoPartenza(BaseModel):
    """
    Dati del trasporto iniziale
    """
    # data type: DatiTrasportoTerrestreModel
    oneof_schema_1_validator: Optional[DatiTrasportoTerrestreModel] = None
    # data type: DatiTrasportoMarittimoModel
    oneof_schema_2_validator: Optional[DatiTrasportoMarittimoModel] = None
    # data type: DatiTrasportoFerroviarioModel
    oneof_schema_3_validator: Optional[DatiTrasportoFerroviarioModel] = None
    if TYPE_CHECKING:
        actual_instance: Union[DatiTrasportoFerroviarioModel, DatiTrasportoMarittimoModel, DatiTrasportoTerrestreModel]
    else:
        actual_instance: Any
    one_of_schemas: List[str] = Field(NUOVOFORMULARIOMODELDATITRASPORTOPARTENZA_ONE_OF_SCHEMAS, const=True)

    class Config:
        validate_assignment = True

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        if v is None:
            return v

        instance = NuovoFormularioModelDatiTrasportoPartenza.construct()
        error_messages = []
        match = 0
        # validate data type: DatiTrasportoTerrestreModel
        if not isinstance(v, DatiTrasportoTerrestreModel):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DatiTrasportoTerrestreModel`")
        else:
            match += 1
        # validate data type: DatiTrasportoMarittimoModel
        if not isinstance(v, DatiTrasportoMarittimoModel):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DatiTrasportoMarittimoModel`")
        else:
            match += 1
        # validate data type: DatiTrasportoFerroviarioModel
        if not isinstance(v, DatiTrasportoFerroviarioModel):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DatiTrasportoFerroviarioModel`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in NuovoFormularioModelDatiTrasportoPartenza with oneOf schemas: DatiTrasportoFerroviarioModel, DatiTrasportoMarittimoModel, DatiTrasportoTerrestreModel. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in NuovoFormularioModelDatiTrasportoPartenza with oneOf schemas: DatiTrasportoFerroviarioModel, DatiTrasportoMarittimoModel, DatiTrasportoTerrestreModel. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> NuovoFormularioModelDatiTrasportoPartenza:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> NuovoFormularioModelDatiTrasportoPartenza:
        """Returns the object represented by the json string"""
        instance = NuovoFormularioModelDatiTrasportoPartenza.construct()
        if json_str is None:
            return instance

        error_messages = []
        match = 0

        # deserialize data into DatiTrasportoTerrestreModel
        try:
            instance.actual_instance = DatiTrasportoTerrestreModel.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DatiTrasportoMarittimoModel
        try:
            instance.actual_instance = DatiTrasportoMarittimoModel.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DatiTrasportoFerroviarioModel
        try:
            instance.actual_instance = DatiTrasportoFerroviarioModel.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into NuovoFormularioModelDatiTrasportoPartenza with oneOf schemas: DatiTrasportoFerroviarioModel, DatiTrasportoMarittimoModel, DatiTrasportoTerrestreModel. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into NuovoFormularioModelDatiTrasportoPartenza with oneOf schemas: DatiTrasportoFerroviarioModel, DatiTrasportoMarittimoModel, DatiTrasportoTerrestreModel. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        to_dict = getattr(self.actual_instance, "to_dict", None)
        if callable(to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.dict())


