# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260119-862
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Operazione(str, Enum):
    """
    Operazione
    """

    """
    allowed enum values
    """
    TRASPORTO = 'Trasporto'
    TRASPORTOUPDATE = 'TrasportoUpdate'
    DATIQUANTITA = 'DatiQuantita'
    DATIQUANTITAUPDATE = 'DatiQuantitaUpdate'
    ACCETTAZIONE = 'Accettazione'
    ALLEGATO = 'Allegato'
    ANNOTAZIONE = 'Annotazione'
    RESET = 'Reset'
    RILASCIA = 'Rilascia'
    ANNULLA = 'Annulla'
    NOTEANNULLAMENTO = 'NoteAnnullamento'
    HASH = 'Hash'
    TRASBORDOTOTALE = 'TrasbordoTotale'
    TRASBORDOPARZIALE = 'TrasbordoParziale'
    SOSTATECNICA = 'SostaTecnica'
    NUOVODESTINATARIO = 'NuovoDestinatario'
    ACQUISIZIONEFIRMA = 'AcquisizioneFirma'
    ACQUISIZIONEFIRMAANNULLAMENTO = 'AcquisizioneFirmaAnnullamento'
    ACQUISIZIONEFIRMATRASPORTATORE = 'AcquisizioneFirmaTrasportatore'
    ACQUISIZIONEFIRMAPRODUTTORE = 'AcquisizioneFirmaProduttore'
    ACQUISIZIONEFIRMAPRODUTTORETRASPORTATORE = 'AcquisizioneFirmaProduttoreTrasportatore'
    ACQUISIZIONEFIRMADESTINATARIO = 'AcquisizioneFirmaDestinatario'
    ACQUISIZIONEFIRMAANNOTAZIONE = 'AcquisizioneFirmaAnnotazione'
    ACQUISIZIONEFIRMATRASBORDOTOTALE = 'AcquisizioneFirmaTrasbordoTotale'
    ACQUISIZIONEFIRMASOSTATECNICA = 'AcquisizioneFirmaSostaTecnica'
    ACQUISIZIONEFIRMATRASBORDOPARZIALE = 'AcquisizioneFirmaTrasbordoParziale'
    ACQUISIZIONEFIRMADESTINATARIOSUCCESSIVO = 'AcquisizioneFirmaDestinatarioSuccessivo'
    ACQUISIZIONEFIRMAACCETTAZIONESUCCESSIVA = 'AcquisizioneFirmaAccettazioneSuccessiva'
    ROLLBACKFIRMA = 'RollbackFirma'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Operazione from a JSON string"""
        return cls(json.loads(json_str))


