# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20251218-834
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class OperazioniRecuperoSmaltimento(str, Enum):
    """
    OperazioniRecuperoSmaltimento
    """

    """
    allowed enum values
    """
    R1 = 'R1'
    R2 = 'R2'
    R3 = 'R3'
    R4 = 'R4'
    R5 = 'R5'
    R6 = 'R6'
    R7 = 'R7'
    R8 = 'R8'
    R9 = 'R9'
    R10 = 'R10'
    R11 = 'R11'
    R12 = 'R12'
    R13 = 'R13'
    D1 = 'D1'
    D2 = 'D2'
    D3 = 'D3'
    D4 = 'D4'
    D5 = 'D5'
    D6 = 'D6'
    D7 = 'D7'
    D8 = 'D8'
    D9 = 'D9'
    D10 = 'D10'
    D11 = 'D11'
    D12 = 'D12'
    D13 = 'D13'
    D14 = 'D14'
    D15 = 'D15'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OperazioniRecuperoSmaltimento from a JSON string"""
        return cls(json.loads(json_str))


