# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20250114-507
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt
from rentri_formulari.models.unita_misura import UnitaMisura

class QuantitaModel(BaseModel):
    """
    QuantitaModel
    """
    valore: Union[StrictFloat, StrictInt] = Field(default=..., description="Quantità (parte intera: 10, parte decimale: 4) compresa tra 0.0000 e 9999999999.9999.")
    unita_misura: UnitaMisura = Field(default=..., description="Unità di misura della quantità  Vedi API di codifica: <i>GET /codifiche/v1.0/unita-misura</i><p>Valori ammessi:<ul style=\"margin:0\"><li><i>kg</i> - Chilogrammi</li><li><i>l</i> - Litri</li></ul></p>")
    __properties = ["valore", "unita_misura"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> QuantitaModel:
        """Create an instance of QuantitaModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> QuantitaModel:
        """Create an instance of QuantitaModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return QuantitaModel.parse_obj(obj)

        _obj = QuantitaModel.parse_obj({
            "valore": obj.get("valore"),
            "unita_misura": obj.get("unita_misura")
        })
        return _obj


