# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260211-891
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist
from rentri_formulari.models.status_response_enum import StatusResponseEnum

class StatusResponse(BaseModel):
    """
    Risposta di stato dell'API  # noqa: E501
    """
    status: Optional[StatusResponseEnum] = Field(default=None, description="Stato dell'API<p>Valori ammessi:<ul style=\"margin:0\"><li><i>Ok</i> - API regolarmente funzionante</li><li><i>Warning</i> - API funzionante, ma con probabili disservizi come indicato nei warning</li></ul></p>")
    warnings: Optional[conlist(StrictStr)] = Field(default=None, description="Eventuali messaggi di warning relativi allo stato dell'API")
    __properties = ["status", "warnings"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> StatusResponse:
        """Create an instance of StatusResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if warnings (nullable) is None
        # and __fields_set__ contains the field
        if self.warnings is None and "warnings" in self.__fields_set__:
            _dict['warnings'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> StatusResponse:
        """Create an instance of StatusResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return StatusResponse.parse_obj(obj)

        _obj = StatusResponse.parse_obj({
            "status": obj.get("status"),
            "warnings": obj.get("warnings")
        })
        return _obj


