# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260119-862
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class StatoFormulario(str, Enum):
    """
    Stati del FIR digitale
    """

    """
    allowed enum values
    """
    INSERIMENTOQUANTITA = 'InserimentoQuantita'
    INSERIMENTOQUANTITATRASPORTOINIZIALE = 'InserimentoQuantitaTrasportoIniziale'
    INSERIMENTOTRASPORTOINIZIALE = 'InserimentoTrasportoIniziale'
    FIRMAPRODUTTORETRASPORTATOREINIZIALE = 'FirmaProduttoreTrasportatoreIniziale'
    FIRMATRASPORTATOREINIZIALE = 'FirmaTrasportatoreIniziale'
    FIRMAPRODUTTORE = 'FirmaProduttore'
    INSERIMENTOTRASPORTOSUCCESSIVO = 'InserimentoTrasportoSuccessivo'
    FIRMATRASPORTATORESUCCESSIVO = 'FirmaTrasportatoreSuccessivo'
    FIRMAANNOTAZIONE = 'FirmaAnnotazione'
    FIRMATRASBORDOPARZIALE = 'FirmaTrasbordoParziale'
    FIRMATRASBORDOTOTALE = 'FirmaTrasbordoTotale'
    FIRMASOSTATECNICA = 'FirmaSostaTecnica'
    FIRMAALLEGATO = 'FirmaAllegato'
    INSERIMENTOACCETTAZIONE = 'InserimentoAccettazione'
    FIRMAACCETTAZIONE = 'FirmaAccettazione'
    ACCETTATO = 'Accettato'
    RESPINTOACCETTATOPARZIALMENTE = 'RespintoAccettatoParzialmente'
    FIRMADESTINATARIOSUCCESSIVO = 'FirmaDestinatarioSuccessivo'
    FIRMAACCETTAZIONESUCCESSIVA = 'FirmaAccettazioneSuccessiva'
    FIRMAANNULLAMENTO = 'FirmaAnnullamento'
    ANNULLATO = 'Annullato'
    INDETERMINATO = 'Indeterminato'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of StatoFormulario from a JSON string"""
        return cls(json.loads(json_str))


