# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260211-891
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class StatiTrasmissioneDati(str, Enum):
    """
    StatiTrasmissioneDati
    """

    """
    allowed enum values
    """
    ATTIVO = 'Attivo'
    ANNULLATO = 'Annullato'

    @classmethod
    def from_json(cls, json_str: str) -> StatiTrasmissioneDati:
        """Create an instance of StatiTrasmissioneDati from a JSON string"""
        return StatiTrasmissioneDati(json.loads(json_str))


