# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260119-862
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class TipiAccettazione(str, Enum):
    """
    TipiAccettazione
    """

    """
    allowed enum values
    """
    A = 'A'
    P = 'P'
    R = 'R'

    @classmethod
    def from_json(cls, json_str: str) -> TipiAccettazione:
        """Create an instance of TipiAccettazione from a JSON string"""
        return TipiAccettazione(json.loads(json_str))


