# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20250114-507
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class TipoTrasporto(str, Enum):
    """
    TipoTrasporto
    """

    """
    allowed enum values
    """
    TERRESTRE = 'Terrestre'
    FERROVIARIO = 'Ferroviario'
    MARITTIMO = 'Marittimo'

    @classmethod
    def from_json(cls, json_str: str) -> TipoTrasporto:
        """Create an instance of TipoTrasporto from a JSON string"""
        return TipoTrasporto(json.loads(json_str))


