# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20250114-507
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class TipoRicerca(str, Enum):
    """
    TipoRicerca
    """

    """
    allowed enum values
    """
    INTRANSITO = 'InTransito'
    ANNULLATI = 'Annullati'
    COMPLETATI = 'Completati'

    @classmethod
    def from_json(cls, json_str: str) -> TipoRicerca:
        """Create an instance of TipoRicerca from a JSON string"""
        return TipoRicerca(json.loads(json_str))


