# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260211-891
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class TipoTrasmissione(str, Enum):
    """
    TipoTrasmissione
    """

    """
    allowed enum values
    """
    SUPPORTO = 'Supporto'
    API = 'Api'
    APPMOBILERENTRI = 'AppMobileRentri'

    @classmethod
    def from_json(cls, json_str: str) -> TipoTrasmissione:
        """Create an instance of TipoTrasmissione from a JSON string"""
        return TipoTrasmissione(json.loads(json_str))


