# coding: utf-8

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20250114-507
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictStr

class TrasmissioneFormularioResponse(BaseModel):
    """
    TrasmissioneFormularioResponse
    """
    identificativo: Optional[StrictStr] = None
    __properties = ["identificativo"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TrasmissioneFormularioResponse:
        """Create an instance of TrasmissioneFormularioResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if identificativo (nullable) is None
        # and __fields_set__ contains the field
        if self.identificativo is None and "identificativo" in self.__fields_set__:
            _dict['identificativo'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TrasmissioneFormularioResponse:
        """Create an instance of TrasmissioneFormularioResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TrasmissioneFormularioResponse.parse_obj(obj)

        _obj = TrasmissioneFormularioResponse.parse_obj({
            "identificativo": obj.get("identificativo")
        })
        return _obj


