# flake8: noqa

# import apis into api package
from rentri_formulari.api.copia_fir_cartaceo_api import CopiaFIRCartaceoApi
from rentri_formulari.api.copia_fir_digitale_api import CopiaFIRDigitaleApi
from rentri_formulari.api.formulario_digitale_api import FormularioDigitaleApi
from rentri_formulari.api.trasmissione_dati_operatore_api import TrasmissioneDatiOperatoreApi
from rentri_formulari.api.trasmissione_dati_soggetto_delegato_api import TrasmissioneDatiSoggettoDelegatoApi
from rentri_formulari.api.default_api import DefaultApi

