# coding: utf-8

# flake8: noqa

"""
    formulari

    Servizio Formulari RENTRI

    The version of the OpenAPI document: 1.0.20260211-891
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.3"

# Define package exports
__all__ = [
    "CopiaFIRCartaceoApi",
    "CopiaFIRDigitaleApi",
    "FormularioDigitaleApi",
    "TrasmissioneDatiOperatoreApi",
    "TrasmissioneDatiSoggettoDelegatoApi",
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AccettazioneItemResult",
    "AnalisiClassificazioneModel",
    "AutorizzazioneModel",
    "AzioniResult",
    "CaratteristichePericolo",
    "CausaliRespingimento",
    "CittaEsteraModel",
    "ComuneModel",
    "ConducenteModel",
    "ControlloFirmeResult",
    "ControlloFormatoResult",
    "ControlloSchemaResult",
    "ControlloVidimazioneResult",
    "CopiaCartaceaConfermaModel",
    "CopiaCartaceaModel",
    "CopiaCartaceaResult",
    "CopiaCartaceaRuoloResult",
    "CopiaCartaceaSoggettoInfo",
    "CopiaDigitaleAccettazioneResult",
    "CopiaDigitaleItemResult",
    "CopiaDigitaleModel",
    "CopiaDigitaleResult",
    "CopiaDigitaleRuoloItemResult",
    "CopiaDigitaleRuoloResult",
    "DatiAccettazioneModel",
    "DatiAccettazioneResultModel",
    "DatiAllegatoModel",
    "DatiAllegatoResultModel",
    "DatiAnnotazioneModel",
    "DatiAnnotazioneResultModel",
    "DatiAnnullamentoModel",
    "DatiAnnullamentoResultModel",
    "DatiDestinatarioFormularioBaseModel",
    "DatiDestinatarioFormularioModel",
    "DatiDestinatarioFormularioResultModel",
    "DatiDestinatarioFormularioSitoModel",
    "DatiDestinatarioSuccessivoResultModel",
    "DatiDestinatarioTrasmissioneModel",
    "DatiDestinazioniSuccessiveResultModel",
    "DatiDestinazioniSuccessiveTrasmissioniModel",
    "DatiFirmaResult",
    "DatiIntermediariFormularioModel",
    "DatiNotificaPushCaricaCopiaDigitaleModel",
    "DatiPartenzaModel",
    "DatiPartenzaModelDestinatario",
    "DatiPartenzaModelProduttore",
    "DatiPartenzaModelTrasportatoriInner",
    "DatiPartenzaResultModel",
    "DatiPerFirmaModel",
    "DatiProduttoreFormularioBaseModel",
    "DatiProduttoreFormularioModel",
    "DatiProduttoreFormularioResultModel",
    "DatiProduttoreFormularioSitoModel",
    "DatiProduttoreOriginarioModel",
    "DatiProduttoreTrasmissioneModel",
    "DatiRifiutoModel",
    "DatiSostaTecnicaModel",
    "DatiSostaTecnicaResultModel",
    "DatiSostaTecnicaTrasmissioneModel",
    "DatiTrasbordoParzialeModel",
    "DatiTrasbordoParzialeOrigineModel",
    "DatiTrasbordoParzialeOrigineResultModel",
    "DatiTrasbordoParzialeResultModel",
    "DatiTrasbordoParzialeTrasmissioneModel",
    "DatiTrasbordoTotaleModel",
    "DatiTrasbordoTotaleResultModel",
    "DatiTrasbordoTotaleTrasmissioneModel",
    "DatiTrasmissioneFormularioModel",
    "DatiTrasmissionePartenzaModel",
    "DatiTrasportatoreFormularioBaseModel",
    "DatiTrasportatoreFormularioModel",
    "DatiTrasportatoreFormularioResultModel",
    "DatiTrasportatoreFormularioSitoModel",
    "DatiTrasportatoreModel",
    "DatiTrasportatoreTrasbordoModel",
    "DatiTrasportatoreTrasmissioneModel",
    "DatiTrasportoBaseModel",
    "DatiTrasportoFerroviarioModel",
    "DatiTrasportoFerroviarioResultModel",
    "DatiTrasportoFerroviarioTrasmissioneModel",
    "DatiTrasportoMarittimoModel",
    "DatiTrasportoMarittimoResultModel",
    "DatiTrasportoMarittimoTrasmissioneModel",
    "DatiTrasportoTerrestreModel",
    "DatiTrasportoTerrestreResultModel",
    "DatiTrasportoTerrestreTrasmissioneModel",
    "DatiTrasportoTrasmissioneBaseModel",
    "DatiTrasportoTrasmissioneBaseModel1",
    "DestinatarioItemResult",
    "DettaglioFormulario",
    "DettaglioFormularioDatiTrasportoInner",
    "DownloadableBaseResponse",
    "EsitoAddAllegatoModel",
    "EsitoAllegatoModel",
    "EsitoCaricaCopiaCartaceaModel",
    "EsitoCaricaCopiaDigitaleModel",
    "EsitoCopiaCartaceaModel",
    "EsitoCopiaDigitaleModel",
    "EsitoCreaFormularioModel",
    "EsitoDatiPerFirmaModel",
    "EsitoEstraiDatiXfirModel",
    "EsitoEstrazioneDatiXfirModel",
    "EsitoFormularioModel",
    "EsitoFormularioModelEsito",
    "EsitoGetHashPerFirmaModel",
    "EsitoMessaggioModel",
    "EsitoMessaggioTipo",
    "EsitoModel",
    "EsitoNuovoFormularioModel",
    "EsitoTrasmissioneDatiModel",
    "EsitoUploadXfirModel",
    "EsitoUploadXfirResultModel",
    "EsitoValidaXfirModel",
    "EsitoValidazione",
    "EsitoValidazioneXfirModel",
    "EstraiDatiXfirModel",
    "FirmaModel",
    "FormularioItemResult",
    "IAnagrafica",
    "IndirizzoModel",
    "IndirizzoModelCitta",
    "InfoFormulario",
    "IntermediarioItemResult",
    "NormativaADRModel",
    "NoteAnnullamentoModel",
    "NumeroFirDestinatarioPostRequest",
    "NumeroFirTrasportoPostRequest",
    "NuovoFormularioModel",
    "NuovoFormularioModelDatiTrasportoPartenza",
    "Operazione",
    "OperazioniRecuperoSmaltimento",
    "ProblemDetails",
    "ProduttoreItemResult",
    "ProprietaDatiNotificaPushCaricaCopiaDigitaleModel",
    "ProvenienzaRifiuto",
    "QuantitaKgModel",
    "QuantitaModel",
    "QuantitaRifiutoModel",
    "RuoloConfermaCopiaCartacea",
    "RuoloConfermaCopiaDigitale",
    "SoggettoItemResult",
    "StatiFisici",
    "StatiTrasmissioneDati",
    "StatoFormulario",
    "StatusResponse",
    "StatusResponseEnum",
    "TipiAccettazione",
    "TipiAutorizzazione",
    "TipoAnalisiClassificazione",
    "TipoFirma",
    "TipoTrasmissione",
    "TipoTrasporto",
    "TransazioneModel",
    "TrasbordoParzialeOrigineResult",
    "TrasmissioneDatiItemResult",
    "TrasmissioneDatiResult",
    "TrasmissioneDatiSitoResult",
    "TrasmissioneFormularioResponse",
    "TrasportatoreItemResult",
    "UnitaMisura",
    "UploadXfirModel",
    "ValidaXfirModel",
    "ValidazioneXfirResult",
    "VidimazioneResult",
]

# import apis into sdk package
from rentri_formulari.api.copia_fir_cartaceo_api import CopiaFIRCartaceoApi as CopiaFIRCartaceoApi
from rentri_formulari.api.copia_fir_digitale_api import CopiaFIRDigitaleApi as CopiaFIRDigitaleApi
from rentri_formulari.api.formulario_digitale_api import FormularioDigitaleApi as FormularioDigitaleApi
from rentri_formulari.api.trasmissione_dati_operatore_api import TrasmissioneDatiOperatoreApi as TrasmissioneDatiOperatoreApi
from rentri_formulari.api.trasmissione_dati_soggetto_delegato_api import TrasmissioneDatiSoggettoDelegatoApi as TrasmissioneDatiSoggettoDelegatoApi
from rentri_formulari.api.default_api import DefaultApi as DefaultApi

# import ApiClient
from rentri_formulari.api_response import ApiResponse as ApiResponse
from rentri_formulari.api_client import ApiClient as ApiClient
from rentri_formulari.configuration import Configuration as Configuration
from rentri_formulari.exceptions import OpenApiException as OpenApiException
from rentri_formulari.exceptions import ApiTypeError as ApiTypeError
from rentri_formulari.exceptions import ApiValueError as ApiValueError
from rentri_formulari.exceptions import ApiKeyError as ApiKeyError
from rentri_formulari.exceptions import ApiAttributeError as ApiAttributeError
from rentri_formulari.exceptions import ApiException as ApiException

# import models into sdk package
from rentri_formulari.models.accettazione_item_result import AccettazioneItemResult as AccettazioneItemResult
from rentri_formulari.models.analisi_classificazione_model import AnalisiClassificazioneModel as AnalisiClassificazioneModel
from rentri_formulari.models.autorizzazione_model import AutorizzazioneModel as AutorizzazioneModel
from rentri_formulari.models.azioni_result import AzioniResult as AzioniResult
from rentri_formulari.models.caratteristiche_pericolo import CaratteristichePericolo as CaratteristichePericolo
from rentri_formulari.models.causali_respingimento import CausaliRespingimento as CausaliRespingimento
from rentri_formulari.models.citta_estera_model import CittaEsteraModel as CittaEsteraModel
from rentri_formulari.models.comune_model import ComuneModel as ComuneModel
from rentri_formulari.models.conducente_model import ConducenteModel as ConducenteModel
from rentri_formulari.models.controllo_firme_result import ControlloFirmeResult as ControlloFirmeResult
from rentri_formulari.models.controllo_formato_result import ControlloFormatoResult as ControlloFormatoResult
from rentri_formulari.models.controllo_schema_result import ControlloSchemaResult as ControlloSchemaResult
from rentri_formulari.models.controllo_vidimazione_result import ControlloVidimazioneResult as ControlloVidimazioneResult
from rentri_formulari.models.copia_cartacea_conferma_model import CopiaCartaceaConfermaModel as CopiaCartaceaConfermaModel
from rentri_formulari.models.copia_cartacea_model import CopiaCartaceaModel as CopiaCartaceaModel
from rentri_formulari.models.copia_cartacea_result import CopiaCartaceaResult as CopiaCartaceaResult
from rentri_formulari.models.copia_cartacea_ruolo_result import CopiaCartaceaRuoloResult as CopiaCartaceaRuoloResult
from rentri_formulari.models.copia_cartacea_soggetto_info import CopiaCartaceaSoggettoInfo as CopiaCartaceaSoggettoInfo
from rentri_formulari.models.copia_digitale_accettazione_result import CopiaDigitaleAccettazioneResult as CopiaDigitaleAccettazioneResult
from rentri_formulari.models.copia_digitale_item_result import CopiaDigitaleItemResult as CopiaDigitaleItemResult
from rentri_formulari.models.copia_digitale_model import CopiaDigitaleModel as CopiaDigitaleModel
from rentri_formulari.models.copia_digitale_result import CopiaDigitaleResult as CopiaDigitaleResult
from rentri_formulari.models.copia_digitale_ruolo_item_result import CopiaDigitaleRuoloItemResult as CopiaDigitaleRuoloItemResult
from rentri_formulari.models.copia_digitale_ruolo_result import CopiaDigitaleRuoloResult as CopiaDigitaleRuoloResult
from rentri_formulari.models.dati_accettazione_model import DatiAccettazioneModel as DatiAccettazioneModel
from rentri_formulari.models.dati_accettazione_result_model import DatiAccettazioneResultModel as DatiAccettazioneResultModel
from rentri_formulari.models.dati_allegato_model import DatiAllegatoModel as DatiAllegatoModel
from rentri_formulari.models.dati_allegato_result_model import DatiAllegatoResultModel as DatiAllegatoResultModel
from rentri_formulari.models.dati_annotazione_model import DatiAnnotazioneModel as DatiAnnotazioneModel
from rentri_formulari.models.dati_annotazione_result_model import DatiAnnotazioneResultModel as DatiAnnotazioneResultModel
from rentri_formulari.models.dati_annullamento_model import DatiAnnullamentoModel as DatiAnnullamentoModel
from rentri_formulari.models.dati_annullamento_result_model import DatiAnnullamentoResultModel as DatiAnnullamentoResultModel
from rentri_formulari.models.dati_destinatario_formulario_base_model import DatiDestinatarioFormularioBaseModel as DatiDestinatarioFormularioBaseModel
from rentri_formulari.models.dati_destinatario_formulario_model import DatiDestinatarioFormularioModel as DatiDestinatarioFormularioModel
from rentri_formulari.models.dati_destinatario_formulario_result_model import DatiDestinatarioFormularioResultModel as DatiDestinatarioFormularioResultModel
from rentri_formulari.models.dati_destinatario_formulario_sito_model import DatiDestinatarioFormularioSitoModel as DatiDestinatarioFormularioSitoModel
from rentri_formulari.models.dati_destinatario_successivo_result_model import DatiDestinatarioSuccessivoResultModel as DatiDestinatarioSuccessivoResultModel
from rentri_formulari.models.dati_destinatario_trasmissione_model import DatiDestinatarioTrasmissioneModel as DatiDestinatarioTrasmissioneModel
from rentri_formulari.models.dati_destinazioni_successive_result_model import DatiDestinazioniSuccessiveResultModel as DatiDestinazioniSuccessiveResultModel
from rentri_formulari.models.dati_destinazioni_successive_trasmissioni_model import DatiDestinazioniSuccessiveTrasmissioniModel as DatiDestinazioniSuccessiveTrasmissioniModel
from rentri_formulari.models.dati_firma_result import DatiFirmaResult as DatiFirmaResult
from rentri_formulari.models.dati_intermediari_formulario_model import DatiIntermediariFormularioModel as DatiIntermediariFormularioModel
from rentri_formulari.models.dati_notifica_push_carica_copia_digitale_model import DatiNotificaPushCaricaCopiaDigitaleModel as DatiNotificaPushCaricaCopiaDigitaleModel
from rentri_formulari.models.dati_partenza_model import DatiPartenzaModel as DatiPartenzaModel
from rentri_formulari.models.dati_partenza_model_destinatario import DatiPartenzaModelDestinatario as DatiPartenzaModelDestinatario
from rentri_formulari.models.dati_partenza_model_produttore import DatiPartenzaModelProduttore as DatiPartenzaModelProduttore
from rentri_formulari.models.dati_partenza_model_trasportatori_inner import DatiPartenzaModelTrasportatoriInner as DatiPartenzaModelTrasportatoriInner
from rentri_formulari.models.dati_partenza_result_model import DatiPartenzaResultModel as DatiPartenzaResultModel
from rentri_formulari.models.dati_per_firma_model import DatiPerFirmaModel as DatiPerFirmaModel
from rentri_formulari.models.dati_produttore_formulario_base_model import DatiProduttoreFormularioBaseModel as DatiProduttoreFormularioBaseModel
from rentri_formulari.models.dati_produttore_formulario_model import DatiProduttoreFormularioModel as DatiProduttoreFormularioModel
from rentri_formulari.models.dati_produttore_formulario_result_model import DatiProduttoreFormularioResultModel as DatiProduttoreFormularioResultModel
from rentri_formulari.models.dati_produttore_formulario_sito_model import DatiProduttoreFormularioSitoModel as DatiProduttoreFormularioSitoModel
from rentri_formulari.models.dati_produttore_originario_model import DatiProduttoreOriginarioModel as DatiProduttoreOriginarioModel
from rentri_formulari.models.dati_produttore_trasmissione_model import DatiProduttoreTrasmissioneModel as DatiProduttoreTrasmissioneModel
from rentri_formulari.models.dati_rifiuto_model import DatiRifiutoModel as DatiRifiutoModel
from rentri_formulari.models.dati_sosta_tecnica_model import DatiSostaTecnicaModel as DatiSostaTecnicaModel
from rentri_formulari.models.dati_sosta_tecnica_result_model import DatiSostaTecnicaResultModel as DatiSostaTecnicaResultModel
from rentri_formulari.models.dati_sosta_tecnica_trasmissione_model import DatiSostaTecnicaTrasmissioneModel as DatiSostaTecnicaTrasmissioneModel
from rentri_formulari.models.dati_trasbordo_parziale_model import DatiTrasbordoParzialeModel as DatiTrasbordoParzialeModel
from rentri_formulari.models.dati_trasbordo_parziale_origine_model import DatiTrasbordoParzialeOrigineModel as DatiTrasbordoParzialeOrigineModel
from rentri_formulari.models.dati_trasbordo_parziale_origine_result_model import DatiTrasbordoParzialeOrigineResultModel as DatiTrasbordoParzialeOrigineResultModel
from rentri_formulari.models.dati_trasbordo_parziale_result_model import DatiTrasbordoParzialeResultModel as DatiTrasbordoParzialeResultModel
from rentri_formulari.models.dati_trasbordo_parziale_trasmissione_model import DatiTrasbordoParzialeTrasmissioneModel as DatiTrasbordoParzialeTrasmissioneModel
from rentri_formulari.models.dati_trasbordo_totale_model import DatiTrasbordoTotaleModel as DatiTrasbordoTotaleModel
from rentri_formulari.models.dati_trasbordo_totale_result_model import DatiTrasbordoTotaleResultModel as DatiTrasbordoTotaleResultModel
from rentri_formulari.models.dati_trasbordo_totale_trasmissione_model import DatiTrasbordoTotaleTrasmissioneModel as DatiTrasbordoTotaleTrasmissioneModel
from rentri_formulari.models.dati_trasmissione_formulario_model import DatiTrasmissioneFormularioModel as DatiTrasmissioneFormularioModel
from rentri_formulari.models.dati_trasmissione_partenza_model import DatiTrasmissionePartenzaModel as DatiTrasmissionePartenzaModel
from rentri_formulari.models.dati_trasportatore_formulario_base_model import DatiTrasportatoreFormularioBaseModel as DatiTrasportatoreFormularioBaseModel
from rentri_formulari.models.dati_trasportatore_formulario_model import DatiTrasportatoreFormularioModel as DatiTrasportatoreFormularioModel
from rentri_formulari.models.dati_trasportatore_formulario_result_model import DatiTrasportatoreFormularioResultModel as DatiTrasportatoreFormularioResultModel
from rentri_formulari.models.dati_trasportatore_formulario_sito_model import DatiTrasportatoreFormularioSitoModel as DatiTrasportatoreFormularioSitoModel
from rentri_formulari.models.dati_trasportatore_model import DatiTrasportatoreModel as DatiTrasportatoreModel
from rentri_formulari.models.dati_trasportatore_trasbordo_model import DatiTrasportatoreTrasbordoModel as DatiTrasportatoreTrasbordoModel
from rentri_formulari.models.dati_trasportatore_trasmissione_model import DatiTrasportatoreTrasmissioneModel as DatiTrasportatoreTrasmissioneModel
from rentri_formulari.models.dati_trasporto_base_model import DatiTrasportoBaseModel as DatiTrasportoBaseModel
from rentri_formulari.models.dati_trasporto_ferroviario_model import DatiTrasportoFerroviarioModel as DatiTrasportoFerroviarioModel
from rentri_formulari.models.dati_trasporto_ferroviario_result_model import DatiTrasportoFerroviarioResultModel as DatiTrasportoFerroviarioResultModel
from rentri_formulari.models.dati_trasporto_ferroviario_trasmissione_model import DatiTrasportoFerroviarioTrasmissioneModel as DatiTrasportoFerroviarioTrasmissioneModel
from rentri_formulari.models.dati_trasporto_marittimo_model import DatiTrasportoMarittimoModel as DatiTrasportoMarittimoModel
from rentri_formulari.models.dati_trasporto_marittimo_result_model import DatiTrasportoMarittimoResultModel as DatiTrasportoMarittimoResultModel
from rentri_formulari.models.dati_trasporto_marittimo_trasmissione_model import DatiTrasportoMarittimoTrasmissioneModel as DatiTrasportoMarittimoTrasmissioneModel
from rentri_formulari.models.dati_trasporto_terrestre_model import DatiTrasportoTerrestreModel as DatiTrasportoTerrestreModel
from rentri_formulari.models.dati_trasporto_terrestre_result_model import DatiTrasportoTerrestreResultModel as DatiTrasportoTerrestreResultModel
from rentri_formulari.models.dati_trasporto_terrestre_trasmissione_model import DatiTrasportoTerrestreTrasmissioneModel as DatiTrasportoTerrestreTrasmissioneModel
from rentri_formulari.models.dati_trasporto_trasmissione_base_model import DatiTrasportoTrasmissioneBaseModel as DatiTrasportoTrasmissioneBaseModel
from rentri_formulari.models.dati_trasporto_trasmissione_base_model1 import DatiTrasportoTrasmissioneBaseModel1 as DatiTrasportoTrasmissioneBaseModel1
from rentri_formulari.models.destinatario_item_result import DestinatarioItemResult as DestinatarioItemResult
from rentri_formulari.models.dettaglio_formulario import DettaglioFormulario as DettaglioFormulario
from rentri_formulari.models.dettaglio_formulario_dati_trasporto_inner import DettaglioFormularioDatiTrasportoInner as DettaglioFormularioDatiTrasportoInner
from rentri_formulari.models.downloadable_base_response import DownloadableBaseResponse as DownloadableBaseResponse
from rentri_formulari.models.esito_add_allegato_model import EsitoAddAllegatoModel as EsitoAddAllegatoModel
from rentri_formulari.models.esito_allegato_model import EsitoAllegatoModel as EsitoAllegatoModel
from rentri_formulari.models.esito_carica_copia_cartacea_model import EsitoCaricaCopiaCartaceaModel as EsitoCaricaCopiaCartaceaModel
from rentri_formulari.models.esito_carica_copia_digitale_model import EsitoCaricaCopiaDigitaleModel as EsitoCaricaCopiaDigitaleModel
from rentri_formulari.models.esito_copia_cartacea_model import EsitoCopiaCartaceaModel as EsitoCopiaCartaceaModel
from rentri_formulari.models.esito_copia_digitale_model import EsitoCopiaDigitaleModel as EsitoCopiaDigitaleModel
from rentri_formulari.models.esito_crea_formulario_model import EsitoCreaFormularioModel as EsitoCreaFormularioModel
from rentri_formulari.models.esito_dati_per_firma_model import EsitoDatiPerFirmaModel as EsitoDatiPerFirmaModel
from rentri_formulari.models.esito_estrai_dati_xfir_model import EsitoEstraiDatiXfirModel as EsitoEstraiDatiXfirModel
from rentri_formulari.models.esito_estrazione_dati_xfir_model import EsitoEstrazioneDatiXfirModel as EsitoEstrazioneDatiXfirModel
from rentri_formulari.models.esito_formulario_model import EsitoFormularioModel as EsitoFormularioModel
from rentri_formulari.models.esito_formulario_model_esito import EsitoFormularioModelEsito as EsitoFormularioModelEsito
from rentri_formulari.models.esito_get_hash_per_firma_model import EsitoGetHashPerFirmaModel as EsitoGetHashPerFirmaModel
from rentri_formulari.models.esito_messaggio_model import EsitoMessaggioModel as EsitoMessaggioModel
from rentri_formulari.models.esito_messaggio_tipo import EsitoMessaggioTipo as EsitoMessaggioTipo
from rentri_formulari.models.esito_model import EsitoModel as EsitoModel
from rentri_formulari.models.esito_nuovo_formulario_model import EsitoNuovoFormularioModel as EsitoNuovoFormularioModel
from rentri_formulari.models.esito_trasmissione_dati_model import EsitoTrasmissioneDatiModel as EsitoTrasmissioneDatiModel
from rentri_formulari.models.esito_upload_xfir_model import EsitoUploadXfirModel as EsitoUploadXfirModel
from rentri_formulari.models.esito_upload_xfir_result_model import EsitoUploadXfirResultModel as EsitoUploadXfirResultModel
from rentri_formulari.models.esito_valida_xfir_model import EsitoValidaXfirModel as EsitoValidaXfirModel
from rentri_formulari.models.esito_validazione import EsitoValidazione as EsitoValidazione
from rentri_formulari.models.esito_validazione_xfir_model import EsitoValidazioneXfirModel as EsitoValidazioneXfirModel
from rentri_formulari.models.estrai_dati_xfir_model import EstraiDatiXfirModel as EstraiDatiXfirModel
from rentri_formulari.models.firma_model import FirmaModel as FirmaModel
from rentri_formulari.models.formulario_item_result import FormularioItemResult as FormularioItemResult
from rentri_formulari.models.i_anagrafica import IAnagrafica as IAnagrafica
from rentri_formulari.models.indirizzo_model import IndirizzoModel as IndirizzoModel
from rentri_formulari.models.indirizzo_model_citta import IndirizzoModelCitta as IndirizzoModelCitta
from rentri_formulari.models.info_formulario import InfoFormulario as InfoFormulario
from rentri_formulari.models.intermediario_item_result import IntermediarioItemResult as IntermediarioItemResult
from rentri_formulari.models.normativa_adr_model import NormativaADRModel as NormativaADRModel
from rentri_formulari.models.note_annullamento_model import NoteAnnullamentoModel as NoteAnnullamentoModel
from rentri_formulari.models.numero_fir_destinatario_post_request import NumeroFirDestinatarioPostRequest as NumeroFirDestinatarioPostRequest
from rentri_formulari.models.numero_fir_trasporto_post_request import NumeroFirTrasportoPostRequest as NumeroFirTrasportoPostRequest
from rentri_formulari.models.nuovo_formulario_model import NuovoFormularioModel as NuovoFormularioModel
from rentri_formulari.models.nuovo_formulario_model_dati_trasporto_partenza import NuovoFormularioModelDatiTrasportoPartenza as NuovoFormularioModelDatiTrasportoPartenza
from rentri_formulari.models.operazione import Operazione as Operazione
from rentri_formulari.models.operazioni_recupero_smaltimento import OperazioniRecuperoSmaltimento as OperazioniRecuperoSmaltimento
from rentri_formulari.models.problem_details import ProblemDetails as ProblemDetails
from rentri_formulari.models.produttore_item_result import ProduttoreItemResult as ProduttoreItemResult
from rentri_formulari.models.proprieta_dati_notifica_push_carica_copia_digitale_model import ProprietaDatiNotificaPushCaricaCopiaDigitaleModel as ProprietaDatiNotificaPushCaricaCopiaDigitaleModel
from rentri_formulari.models.provenienza_rifiuto import ProvenienzaRifiuto as ProvenienzaRifiuto
from rentri_formulari.models.quantita_kg_model import QuantitaKgModel as QuantitaKgModel
from rentri_formulari.models.quantita_model import QuantitaModel as QuantitaModel
from rentri_formulari.models.quantita_rifiuto_model import QuantitaRifiutoModel as QuantitaRifiutoModel
from rentri_formulari.models.ruolo_conferma_copia_cartacea import RuoloConfermaCopiaCartacea as RuoloConfermaCopiaCartacea
from rentri_formulari.models.ruolo_conferma_copia_digitale import RuoloConfermaCopiaDigitale as RuoloConfermaCopiaDigitale
from rentri_formulari.models.soggetto_item_result import SoggettoItemResult as SoggettoItemResult
from rentri_formulari.models.stati_fisici import StatiFisici as StatiFisici
from rentri_formulari.models.stati_trasmissione_dati import StatiTrasmissioneDati as StatiTrasmissioneDati
from rentri_formulari.models.stato_formulario import StatoFormulario as StatoFormulario
from rentri_formulari.models.status_response import StatusResponse as StatusResponse
from rentri_formulari.models.status_response_enum import StatusResponseEnum as StatusResponseEnum
from rentri_formulari.models.tipi_accettazione import TipiAccettazione as TipiAccettazione
from rentri_formulari.models.tipi_autorizzazione import TipiAutorizzazione as TipiAutorizzazione
from rentri_formulari.models.tipo_analisi_classificazione import TipoAnalisiClassificazione as TipoAnalisiClassificazione
from rentri_formulari.models.tipo_firma import TipoFirma as TipoFirma
from rentri_formulari.models.tipo_trasmissione import TipoTrasmissione as TipoTrasmissione
from rentri_formulari.models.tipo_trasporto import TipoTrasporto as TipoTrasporto
from rentri_formulari.models.transazione_model import TransazioneModel as TransazioneModel
from rentri_formulari.models.trasbordo_parziale_origine_result import TrasbordoParzialeOrigineResult as TrasbordoParzialeOrigineResult
from rentri_formulari.models.trasmissione_dati_item_result import TrasmissioneDatiItemResult as TrasmissioneDatiItemResult
from rentri_formulari.models.trasmissione_dati_result import TrasmissioneDatiResult as TrasmissioneDatiResult
from rentri_formulari.models.trasmissione_dati_sito_result import TrasmissioneDatiSitoResult as TrasmissioneDatiSitoResult
from rentri_formulari.models.trasmissione_formulario_response import TrasmissioneFormularioResponse as TrasmissioneFormularioResponse
from rentri_formulari.models.trasportatore_item_result import TrasportatoreItemResult as TrasportatoreItemResult
from rentri_formulari.models.unita_misura import UnitaMisura as UnitaMisura
from rentri_formulari.models.upload_xfir_model import UploadXfirModel as UploadXfirModel
from rentri_formulari.models.valida_xfir_model import ValidaXfirModel as ValidaXfirModel
from rentri_formulari.models.validazione_xfir_result import ValidazioneXfirResult as ValidazioneXfirResult
from rentri_formulari.models.vidimazione_result import VidimazioneResult as VidimazioneResult

